### ISSUE TITLE
SIGSEGV on Raspberry Pi

### ISSUE THREAD

**Issue by oligu** [pythonnet/pythonnet#1351] opened 2021-01-11 11:10 UTC
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.6.11
-   Operating System: Raspian (Debian 9)
-   .NET Runtime: mono 6.12.0.107

### Details

-   Describe what you were trying to get done.

    Get pythonnet running on a Raspberry Pi

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```console
$ python3 -c "import clr"
```

-   If there was a crash, please include the traceback here.

```console
=================================================================
        Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
        Native stacktrace:
=================================================================
        0x7fa2c4e758 - /usr/lib/libmonosgen-2.0.so.1 : 
        0x7fa2c4ea74 - /usr/lib/libmonosgen-2.0.so.1 : 
        0x7fa2c09ab8 - /usr/lib/libmonosgen-2.0.so.1 : 
        0x7fa2b87224 - /usr/lib/libmonosgen-2.0.so.1 : 
        0x7fa39e75b8 - linux-vdso.so.1 : __kernel_rt_sigreturn

=================================================================
        Telemetry Dumper:
=================================================================
Pkilling 0x548145893856x from 0x548205857600x
Entering thread summarizer pause from 0x548205857600x
Could not exec mono-hang-watchdog, expected on path '/etc/../bin/mono-hang-watchdog' (errno 2)
Finished thread summarizer pause from 0x548205857600x.
Failed to create breadcrumb file (null)/crash_hash_0x0

Waiting for dumping threads to resume

=================================================================
        External Debugger Dump:
=================================================================
[New LWP 1685]
[New LWP 1686]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
0x0000007fa365de08 in __waitpid (pid=<optimized out>, stat_loc=0x7ffb9f09bc, options=<optimized out>) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30      ../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id                                    Frame 
* 1    Thread 0x7fa39d8b40 (LWP 1684) "python3"     0x0000007fa365de08 in __waitpid (pid=<optimized out>, stat_loc=0x7ffb9f09bc, options=<optimized out>) at ../sysdeps/unix/sysv/linux/waitpid.c:30
  2    Thread 0x7fa23ff1e0 (LWP 1685) "SGen worker" futex_wait_cancelable (private=0, expected=0, futex_word=0x7fa2faf968) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  3    Thread 0x7fa00a91e0 (LWP 1686) "Finalizer"   futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7fa2fa1318) at ../sysdeps/unix/sysv/linux/futex-internal.h:205

Thread 3 (Thread 0x7fa00a91e0 (LWP 1686)):
#0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7fa2fa1318) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x7fa2fa1318, abstime=0x0) at sem_waitcommon.c:111
#2  0x0000007fa365c110 in __new_sem_wait_slow (sem=0x7fa2fa1318, abstime=0x0) at sem_waitcommon.c:181
#3  0x0000007fa2db9af4 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#4  0x0000007fa2d794d4 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#5  0x0000007fa36537e4 in start_thread (arg=0x7ffb9f143f) at pthread_create.c:486
#6  0x0000007fa34c4adc in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78

Thread 2 (Thread 0x7fa23ff1e0 (LWP 1685)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x7fa2faf968) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7fa2faf8f0, cond=0x7fa2faf940) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7fa2faf940, mutex=0x7fa2faf8f0) at pthread_cond_wait.c:655
#3  0x0000007fa2e08d44 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#4  0x0000007fa36537e4 in start_thread (arg=0x7ffb9f14df) at pthread_create.c:486
#5  0x0000007fa34c4adc in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78

Thread 1 (Thread 0x7fa39d8b40 (LWP 1684)):
#0  0x0000007fa365de08 in __waitpid (pid=<optimized out>, stat_loc=0x7ffb9f09bc, options=<optimized out>) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x0000007fa2c4e990 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#2  0x0000007fa2c4ea74 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#3  0x0000007fa2c09ab8 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#4  0x0000007fa2b87224 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#5  <signal handler called>
#6  0x0000000000000000 in ?? ()
#7  0x0000007fa37e40b8 in subtract_refs (containers=<optimized out>) at Modules/gcmodule.c:399
#8  collect (generation=generation@entry=2, n_collected=n_collected@entry=0x7ffb9f2c20, n_uncollectable=n_uncollectable@entry=0x7ffb9f2c28, nofail=nofail@entry=0) at Modules/gcmodule.c:953
#9  0x0000007fa385e584 in collect_with_callback (generation=generation@entry=2) at Modules/gcmodule.c:1128
#10 0x0000007fa385e768 in PyGC_Collect () at Modules/gcmodule.c:1594
#11 0x0000007fa385e728 in _PyGC_CollectIfEnabled () at Modules/gcmodule.c:1608
#12 0x0000007fa385342c in Py_FinalizeEx () at Python/pylifecycle.c:599
#13 0x0000007fa385d590 in Py_Main (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:830
#14 0x000000555a429d44 in main (argc=3, argv=0x7ffb9f2f68) at ./Programs/python.c:69
[Inferior 1 (process 1684) detached]

=================================================================
        Basic Fault Address Reporting
=================================================================
instruction pointer is NULL, skip dumping
=================================================================
        Managed Stacktrace:
=================================================================
=================================================================
Aborted (core dumped)
```

**Comment by filmor** [comment] 2021-01-11 12:24
Duplicate of #898.

**Closed by filmor** 2021-01-11 12:24 UTC
