### ISSUE TITLE
pythonnet build installation failing

### ISSUE THREAD

**Issue by ilonadem** [pythonnet/pythonnet#1470] opened 2021-06-09 10:58 UTC
### Environment

-   Pythonnet version: latest
-   Python version: 3.8.5
-   Operating System: macOS, also tried on Linux

### Details

- Trying to install pythonnet. Have tried installing mono-roslyn (as per issue #1223, and have langver 7.3 installed, which haven't changed the error messages produced.

-  first tried doing:

`pip install pythonnet `

which gave the following error message:

```
  Build started 06/09/2021 10:52:15.
  __________________________________________________
  Project "/tmp/pip-install-sq2tkah9/pythonnet_2915ea9cc9b74b4abd3693a889e5c317/pythonnet.sln" (Build target(s)):
        Target ValidateSolutionConfiguration:
                Building solution configuration "ReleaseMono|x64".
        Target Build:
                Project "/tmp/pip-install-sq2tkah9/pythonnet_2915ea9cc9b74b4abd3693a889e5c317/src/runtime/Python.Runtime.csproj" (default target(s)):
                        Target PrepareForBuild:
                                Configuration: ReleaseMono Platform: x64
                                Created directory "bin/"
                        Target GenerateSatelliteAssemblies:
                        No input files were specified for target GenerateSatelliteAssemblies, skipping.
                        Target CoreCompile:
                                Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:pdbonly /optimize+ /out:obj/x64/ReleaseMono/Python.Runtime.dll /resource:obj/x64/ReleaseMono/Python.Runtime.resources.clr.py,clr.py Codecs/EncoderGroup.cs Codecs/DecoderGroup.cs Codecs/RawProxyEncoder.cs Codecs/TupleCodecs.cs converterextensions.cs finalizer.cs Properties/AssemblyInfo.cs ../SharedAssemblyInfo.cs arrayobject.cs assemblymanager.cs BorrowedReference.cs classderived.cs classbase.cs classmanager.cs classobject.cs clrobject.cs codegenerator.cs constructorbinder.cs constructorbinding.cs converter.cs CustomMarshaler.cs debughelper.cs delegatemanager.cs delegateobject.cs eventbinding.cs eventobject.cs exceptions.cs extensiontype.cs fieldobject.cs generictype.cs genericutil.cs importhook.cs indexer.cs interfaceobject.cs interfaces.cs interop.cs iterator.cs managedtype.cs metatype.cs methodbinder.cs methodbinding.cs methodobject.cs methodwrapper.cs modulefunctionobject.cs moduleobject.cs modulepropertyobject.cs nativecall.cs NewReference.cs NonCopyableAttribute.cs overload.cs propertyobject.cs pyansistring.cs pydict.cs PyExportAttribute.cs pyfloat.cs pyint.cs pyiter.cs pylist.cs pylong.cs pynumber.cs pyobject.cs pyscope.cs pysequence.cs pystring.cs pythonengine.cs pythonexception.cs pytuple.cs ReferenceExtensions.cs runtime.cs typemanager.cs typemethod.cs Util.cs platform/Types.cs platform/LibraryLoader.cs polyfill/ReflectionPolifills.cs slots/mp_length.cs interop38.cs obj/x64/ReleaseMono/.NETFramework,Version=v4.0.AssemblyAttribute.cs /target:library /unsafe+ /define:"PYTHON38;PYTHON3;UCS4;MONO_LINUX;PYTHON_WITHOUT_ENABLE_SHARED" /nowarn:1591 /doc:bin/Python.Runtime.xml /langversion:7.3 /nostdlib /reference:/usr/lib/mono/4.0-api/System.dll /reference:/usr/lib/mono/4.0-api/System.Core.dll /reference:/usr/lib/mono/4.0-api//mscorlib.dll
  CSC: error CS1617: Invalid -langversion option `7.3'. It must be `ISO-1', `ISO-2', Default, Latest or value in range 1 to 7.2
                        Task "Csc" execution -- FAILED
                        Done building target "CoreCompile" in project "/tmp/pip-install-sq2tkah9/pythonnet_2915ea9cc9b74b4abd3693a889e5c317/src/runtime/Python.Runtime.csproj".-- FAILED
                Done building project "/tmp/pip-install-sq2tkah9/pythonnet_2915ea9cc9b74b4abd3693a889e5c317/src/runtime/Python.Runtime.csproj".-- FAILED
        Task "MSBuild" execution -- FAILED
        Done building target "Build" in project "/tmp/pip-install-sq2tkah9/pythonnet_2915ea9cc9b74b4abd3693a889e5c317/pythonnet.sln".-- FAILED
  Done building project "/tmp/pip-install-sq2tkah9/pythonnet_2915ea9cc9b74b4abd3693a889e5c317/pythonnet.sln".-- FAILED
  
  Build FAILED.
  Errors:
  
  /tmp/pip-install-sq2tkah9/pythonnet_2915ea9cc9b74b4abd3693a889e5c317/pythonnet.sln (Build) ->
  (Build target) ->
  /tmp/pip-install-sq2tkah9/pythonnet_2915ea9cc9b74b4abd3693a889e5c317/src/runtime/Python.Runtime.csproj (default targets) ->
  /usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->
  
        CSC: error CS1617: Invalid -langversion option `7.3'. It must be `ISO-1', `ISO-2', Default, Latest or value in range 1 to 7.2
  
         0 Warning(s)
         1 Error(s)
  
  Time Elapsed 00:00:00.7397050
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-sq2tkah9/pythonnet_2915ea9cc9b74b4abd3693a889e5c317/setup.py", line 630, in <module>
      setup(
    File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-sq2tkah9/pythonnet_2915ea9cc9b74b4abd3693a889e5c317/setup.py", line 612, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "/usr/local/lib/python3.8/dist-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-sq2tkah9/pythonnet_2915ea9cc9b74b4abd3693a889e5c317/setup.py", line 353, in build_extension
      subprocess.check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON38%3BPYTHON3%3BUCS4%3BMONO_LINUX%3BPYTHON_WITHOUT_ENABLE_SHARED" /p:PythonBuildDir="/tmp/pip-install-sq2tkah9/pythonnet_2915ea9cc9b74b4abd3693a889e5c317/build/lib.linux-x86_64-3.8" /p:PythonInteropFile="interop38.cs" /p:PackageId=pythonnet_py38_x64 /verbosity:normal /t:Build' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sq2tkah9/pythonnet_2915ea9cc9b74b4abd3693a889e5c317/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sq2tkah9/pythonnet_2915ea9cc9b74b4abd3693a889e5c317/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0x2h945n/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/user/.local/include/python3.8/pythonnet
         cwd: /tmp/pip-install-sq2tkah9/pythonnet_2915ea9cc9b74b4abd3693a889e5c317/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sq2tkah9/pythonnet_2915ea9cc9b74b4abd3693a889e5c317/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sq2tkah9/pythonnet_2915ea9cc9b74b4abd3693a889e5c317/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0x2h945n/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/user/.local/include/python3.8/pythonnet Check the logs for full command output.
```

- have also tried:
```python
    pip install git+https://github.com/pythonnet/pythonnet
```

which produces the following traceback:

```python
  Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/user/.local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpwatfmmnp
       cwd: /tmp/pip-req-build-41soyw9d
  Complete output (15 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  copying clr.py -> build/lib
  creating build/lib/pythonnet
  copying pythonnet/__init__.py -> build/lib/pythonnet
  creating build/lib/pythonnet/find_libpython
  copying pythonnet/find_libpython/__main__.py -> build/lib/pythonnet/find_libpython
  copying pythonnet/find_libpython/__init__.py -> build/lib/pythonnet/find_libpython
  running build_dotnet
  Running dotnet build...
  dotnet build src/runtime/Python.Runtime.csproj --configuration release --output /tmp/pip-req-build-41soyw9d/build/lib/pythonnet/runtime
  error: command 'dotnet' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
Failed to build pythonnet
ERROR: Could not build wheels for pythonnet which use PEP 517 and cannot be installed directly
```

**Comment by filmor** [comment] 2021-06-09 12:10
Could you check the repository out locally and run `dotnet build` in there once?

**Comment by ilonadem** [comment] 2021-06-09 13:21
@filmor cloned the repo locally, but the `dotnet build` command is not recognized, and returns `bash: dotnet: command not found`

**Comment by ilonadem** [comment] 2021-06-09 13:30
When I try to run `pip install pythonnet` from within the repo I get the same errors as before

**Comment by ilonadem** [comment] 2021-06-09 16:12
Cloned the repo and ran `dotnet build`, and got:
```
Microsoft (R) Build Engine version 16.10.1+2fd48ab73 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /Users/ilonademler/Desktop/pythonnet/tests/domain_tests/Python.DomainReloadTests.csproj (in 24.94 sec).
  Restored /Users/ilonademler/Desktop/pythonnet/src/runtime/Python.Runtime.csproj (in 26.79 sec).
  Restored /Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj (in 26.8 sec).
  Restored /Users/ilonademler/Desktop/pythonnet/src/perf_tests/Python.PerformanceTests.csproj (in 26.93 sec).
  Restored /Users/ilonademler/Desktop/pythonnet/src/console/Console.csproj (in 28.93 sec).
  Restored /Users/ilonademler/Desktop/pythonnet/src/embed_tests/Python.EmbeddingTest.csproj (in 29.79 sec).
  Restored /Users/ilonademler/Desktop/pythonnet/src/python_tests_runner/Python.PythonTestsRunner.csproj (in 29.8 sec).
  Python.PerformanceTests -> /Users/ilonademler/Desktop/pythonnet/src/perf_tests/bin/x64/Debug/net472/Python.PerformanceTests.dll
/Users/ilonademler/Desktop/pythonnet/src/runtime/typemanager.cs(591,22): warning CS1030: #warning: 'dead code?' [/Users/ilonademler/Desktop/pythonnet/src/runtime/Python.Runtime.csproj]
/Users/ilonademler/Desktop/pythonnet/src/runtime/converter.cs(877,31): warning CS0612: 'Runtime.PySequence_Size(IntPtr)' is obsolete [/Users/ilonademler/Desktop/pythonnet/src/runtime/Python.Runtime.csproj]
/Users/ilonademler/Desktop/pythonnet/src/runtime/managedtype.cs(105,28): warning CS8600: Converting null literal or possible null value to non-nullable type. [/Users/ilonademler/Desktop/pythonnet/src/runtime/Python.Runtime.csproj]
/Users/ilonademler/Desktop/pythonnet/src/runtime/methodbinder.cs(375,34): warning CS0612: 'Runtime.PyDict_Keys(IntPtr)' is obsolete [/Users/ilonademler/Desktop/pythonnet/src/runtime/Python.Runtime.csproj]
  Python.Runtime -> /Users/ilonademler/Desktop/pythonnet/pythonnet/runtime/Python.Runtime.dll
  Python.EmbeddingTest -> /Users/ilonademler/Desktop/pythonnet/src/embed_tests/bin/Debug/net472/Python.EmbeddingTest.dll
  Console -> /Users/ilonademler/Desktop/pythonnet/src/console/bin/x64/Debug/net472/nPython.exe
  Console -> /Users/ilonademler/Desktop/pythonnet/src/console/bin/x64/Debug/netcoreapp3.1/nPython.dll
/Users/ilonademler/Desktop/pythonnet/src/runtime/typemanager.cs(591,22): warning CS1030: #warning: 'dead code?' [/Users/ilonademler/Desktop/pythonnet/src/runtime/Python.Runtime.csproj]
/Users/ilonademler/Desktop/pythonnet/src/runtime/converter.cs(877,31): warning CS0612: 'Runtime.PySequence_Size(IntPtr)' is obsolete [/Users/ilonademler/Desktop/pythonnet/src/runtime/Python.Runtime.csproj]
/Users/ilonademler/Desktop/pythonnet/src/runtime/managedtype.cs(105,28): warning CS8600: Converting null literal or possible null value to non-nullable type. [/Users/ilonademler/Desktop/pythonnet/src/runtime/Python.Runtime.csproj]
/Users/ilonademler/Desktop/pythonnet/src/runtime/methodbinder.cs(375,34): warning CS0612: 'Runtime.PyDict_Keys(IntPtr)' is obsolete [/Users/ilonademler/Desktop/pythonnet/src/runtime/Python.Runtime.csproj]
  Python.Runtime -> /Users/ilonademler/Desktop/pythonnet/src/runtime/bin/for_perf/Python.Runtime.dll
  Python.EmbeddingTest -> /Users/ilonademler/Desktop/pythonnet/src/embed_tests/bin/Debug/netcoreapp3.1/Python.EmbeddingTest.dll
  Python.DomainReloadTests -> /Users/ilonademler/Desktop/pythonnet/tests/domain_tests/bin/net472/Python.DomainReloadTests.exe
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
  Python.Test -> /Users/ilonademler/Desktop/pythonnet/src/testing/bin/Debug/netstandard2.0/Python.Test.dll
  Python.PythonTestsRunner -> /Users/ilonademler/Desktop/pythonnet/src/python_tests_runner/bin/Debug/netcoreapp3.1/Python.PythonTestsRunner.dll
  Python.PythonTestsRunner -> /Users/ilonademler/Desktop/pythonnet/src/python_tests_runner/bin/Debug/net472/Python.PythonTestsRunner.dll
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
  Python.Test -> /Users/ilonademler/Desktop/pythonnet/src/testing/bin/Debug/net5.0/Python.Test.dll

Build succeeded.

/Users/ilonademler/Desktop/pythonnet/src/runtime/typemanager.cs(591,22): warning CS1030: #warning: 'dead code?' [/Users/ilonademler/Desktop/pythonnet/src/runtime/Python.Runtime.csproj]
/Users/ilonademler/Desktop/pythonnet/src/runtime/converter.cs(877,31): warning CS0612: 'Runtime.PySequence_Size(IntPtr)' is obsolete [/Users/ilonademler/Desktop/pythonnet/src/runtime/Python.Runtime.csproj]
/Users/ilonademler/Desktop/pythonnet/src/runtime/managedtype.cs(105,28): warning CS8600: Converting null literal or possible null value to non-nullable type. [/Users/ilonademler/Desktop/pythonnet/src/runtime/Python.Runtime.csproj]
/Users/ilonademler/Desktop/pythonnet/src/runtime/methodbinder.cs(375,34): warning CS0612: 'Runtime.PyDict_Keys(IntPtr)' is obsolete [/Users/ilonademler/Desktop/pythonnet/src/runtime/Python.Runtime.csproj]
/Users/ilonademler/Desktop/pythonnet/src/runtime/typemanager.cs(591,22): warning CS1030: #warning: 'dead code?' [/Users/ilonademler/Desktop/pythonnet/src/runtime/Python.Runtime.csproj]
/Users/ilonademler/Desktop/pythonnet/src/runtime/converter.cs(877,31): warning CS0612: 'Runtime.PySequence_Size(IntPtr)' is obsolete [/Users/ilonademler/Desktop/pythonnet/src/runtime/Python.Runtime.csproj]
/Users/ilonademler/Desktop/pythonnet/src/runtime/managedtype.cs(105,28): warning CS8600: Converting null literal or possible null value to non-nullable type. [/Users/ilonademler/Desktop/pythonnet/src/runtime/Python.Runtime.csproj]
/Users/ilonademler/Desktop/pythonnet/src/runtime/methodbinder.cs(375,34): warning CS0612: 'Runtime.PyDict_Keys(IntPtr)' is obsolete [/Users/ilonademler/Desktop/pythonnet/src/runtime/Python.Runtime.csproj]
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
CSC : warning AD0001: Analyzer 'NonCopyable.NonCopyableAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.Operations.ArrayInitializerOperation' to type 'Microsoft.CodeAnalysis.Operations.IArrayCreationOperation'.'. [/Users/ilonademler/Desktop/pythonnet/src/testing/Python.Test.csproj]
    18 Warning(s)
    0 Error(s)

Time Elapsed 00:00:39.50
```

does this mean that pythonnet should work now?

**Comment by filmor** [comment] 2021-06-11 05:19
And `python setup.py build` doesn't run from the repository? Can you try rerunning `pip install` now? I'll close this issue, as far as I can see the problem is your environment.

For building 2.5 you need a working installation of `mono`. You say that you have "langver 7.3 installed", but if that was the case this error would not appear. My guess is that the wrong `xbuild` or `mcs` binaries are picked up.

For building the current master, you only need the .NET 5 SDK. Since your build from the cloned repository worked fine, you can just use `pip install .` from this directory.

**Closed by filmor** 2021-06-11 05:19 UTC
