### ISSUE TITLE
Converter.ToManagedValue method cannot convert python dictionary into c# dictionary

### ISSUE THREAD

**Issue by devunt** [pythonnet/pythonnet#629] opened 2018-02-17 12:02 UTC
I'm not sure whether #623 handles this issue too, so I'm opening this issue separately.

`Converter.ToManagedValue` is missing dictionary handling when convert python dictionary into c# object.
https://github.com/pythonnet/pythonnet/blob/master/src/runtime/converter.cs#L346-L374

**Comment by denfromufa** [comment] 2018-02-18 02:15
@devunt this may be possible for python 3.5+, if on python side the collections enforce the typing annotations:

http://mypy.readthedocs.io/en/latest/builtin_types.html

**Comment by denfromufa** [comment] 2018-02-18 02:16
cc @yagweb

**Comment by yagweb** [comment] 2018-02-22 06:38
@devunt I think it's not a good choice to add the c# dictionary handling logic to the internal Converter currently, the converter is very complex already and it is heavily used by many components. The PyConverter  #623 can be used for c# dictionary. Its design is not that well. I will try to bring this function into pythonnet after detailed design.

@denfromufa There are many issues caused by the converter and many requirements related to it. But the internal converter is too complex. I was working on a new converter system considering both the internal Converter and my PyConverter.  

The basic idea here is, building a general convert framework at the bottom, then comes the internal converter and customize converter services.

It will take me some time.

**Comment by denfromufa** [comment] 2018-02-22 15:18
@yagweb i agree having basic converter at the core and converter for containers in other high-level APIs.

**Comment by B4rtware** [comment] 2019-05-12 11:20
@yagweb I would love to hear some news about your progress you have already made.

**Comment by yagweb** [comment] 2019-05-14 09:37
Sorry for little progress. 

I changed my job last year, all my time has been put in the new job. I may have no spare time until late this year.



hbtmdxywg@126.com
 
From: B4rtware
Date: 2019-05-12 19:20
To: pythonnet/pythonnet
CC: Wenguang Yang; Mention
Subject: Re: [pythonnet/pythonnet] Converter.ToManagedValue method cannot convert python dictionary into c# dictionary (#629)
@yagweb I would love to hear some news about your progress you have already made.

**Comment by B4rtware** [comment] 2019-05-17 00:35
No problem. Allright, have a nice day :D

**Comment by filmor** [comment] 2022-06-14 13:46
This is out of scope. Codecs could be used for this and we would accept a PR that adds one to the codec library, but this will never be the default.

**Closed by filmor** 2022-06-14 13:46 UTC
