### ISSUE TITLE
Managed exception from Python code is always transformed to PythonException

### ISSUE THREAD

**Issue by tibortakacs** [pythonnet/pythonnet#1443] opened 2021-04-16 19:14 UTC
### Environment

-   Pythonnet version: 3.0.0 preview
-   Python version: 3.8 win32
-   Operating System: Windows
-   .NET Runtime: .NET 5

### Summary

If there is a callback from .NET to Python, and the Python code raises a .NET type exception, instead of the corresponding real .NET exception was rethrown on the .NET side (after marshalling), always `Python.Runtime.PythonException` is thrown.

### Details

.NET snippet
```C#
class Foo
{
    public static void Bar(Action action)
    {
        try
        {
            action.Invoke();
            Console.WriteLine("No exception.");
        }
        catch (NullReferenceException)
        {
            Console.WriteLine("Null reference caught.");
        }
        catch (Exception ex)
        {
             Console.WriteLine("General exception caught: " + ex.GetType().Type); 
        }
    }
}
```

Python snippet
```Python
# .NET imports
from System import NullReferenceException, Action
from MyProgram import Foo

# Preparation
def call():
    raise NullReferenceException()

action = Action(call)

# Action
Foo.Bar(action)
```

Expected output:
`Null reference caught.`

Actual output:
`General exception caught: Python.Runtime.PythonException`

**Comment by lostmsu** [comment] 2021-04-16 19:17
In 2.x this is by design.
In 3.x the work is already in progress: https://github.com/pythonnet/pythonnet/pull/1134

**Comment by tibortakacs** [comment] 2021-04-16 19:26
@lostmsu Amazing, thank you. I see great progress has been achieved there.

Is there any workaround in the meantime that you can recommend?
Can I ask whether there is an estimation of merging this back into master? (Just asking this because if it will be available in the near future, I do not redesign our code with a workaround.)

**Comment by lostmsu** [comment] 2021-04-16 19:36
@tibortakacs you can try simply using the branch from the PR.

**Comment by tibortakacs** [comment] 2021-04-16 20:12
@lostmsu Amazing, it works properly, not only in the simplified code but also in the real application. Based on this great progress, is it fair to say that there is a chance that it will be merged back into `master` in the next few weeks? (I am really sorry if my question seems to be "pushy", I am just more comfortable releasing our application based on the `master` if possible.)

**Comment by lostmsu** [comment] 2021-04-16 20:16
A chance, yes. But I can not guarantee you that. I'd probably be more certain about the end of May.

**Comment by tibortakacs** [comment] 2021-04-16 20:29
@lostmsu Thank you, looking forward to it. If there any way I can support your work (e.g. I am happy to test it with our application regularly), please let me know.

**Comment by lostmsu** [comment] 2021-09-23 06:47
Corresponding PR has been merged

**Closed by lostmsu** 2021-09-23 06:47 UTC
