### ISSUE TITLE
Type conversion changes between 2.1.0dev and 2.1.0

### ISSUE THREAD

**Issue by josselex** [pythonnet/pythonnet#236] opened 2016-06-29 15:01 UTC
I have a method with the signature
Memory.GetActive(out int s32MemId)
Memory.GetActive(out System.IntPtr ptr)

With 2.1.0dev it was possible to call 

``` python
_,out=obj.Memory.GetActive(0)
```

But this now returns

```
TypeError: No method matches given arguments
```

and I have to do:

``` python
_,out=obj.Memory.GetActive(System.Int32(0))
```

What changed and why did it change (i did not find something about this change)?
The new code ist much more verbose, is it possible to get the old behaviour back?

**Comment by vmuriart** [comment] 2016-06-29 15:12
See related https://github.com/pythonnet/pythonnet/issues/203 and https://github.com/pythonnet/pythonnet/pull/217

It was to close a bug, but introduced unexpected behavior

**Comment by denfromufa** [comment] 2016-06-29 15:22
First of all #217 is un-merged pull request for parent-child class overloads.

This problem is related to out/ref arguments:

https://github.com/pythonnet/pythonnet/pull/227

**Comment by filmor** [comment] 2020-06-09 15:12
Since there have not been any updates in quite a while, I'll close this issue. Feel free to reopen and provide a information on the current state.

**Closed by filmor** 2020-06-09 15:12 UTC
Labels: bug
