### ISSUE TITLE
Install failure with Python 3.6.8, Cent OS 7, .NET 5

### ISSUE THREAD

**Issue by shugaoye** [pythonnet/pythonnet#1435] opened 2021-04-06 09:47 UTC
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.6.8
-   Operating System: CentOS 7
-   .NET Runtime: 5.0.201

### Details

-   Describe what you were trying to get done.

    $ sudo pip install pythonnet

-   What commands did you run to trigger this issue? 

```bash
$ python -V
Python 3.6.8

$ mono --version
Mono JIT compiler version 6.8.0.123 (tarball Mon Feb 22 21:52:52 UTC 2021)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.201/

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  5.0.201 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

-   If there was a crash, please include the traceback here.

```bash
$ pip install pythonnet
...
Collecting pythonnet                                                                                                      Downloading http://pypi.doubanio.com/packages/f7/18/be276f27f649199563a59561623c0c008e72bbcb6ecb8b2ca0404a741ae1/pythonnet-2.5.2.tar.gz (1.9 MB)                                                                                                   |████████████████████████████████| 1.9 MB 2.6 MB/s                                                                 Requirement already satisfied: pycparser in ./.venvs/kpclib/lib/python3.6/site-packages (from pythonnet) (2.20)         Building wheels for collected packages: pythonnet                                                                         Building wheel for pythonnet (setup.py) ... error                                                                       ERROR: Command errored out with exit status 1:                                                                           command: /home/epm-user/.venvs/kpclib/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/setup.py'"'"'; __file__='"'"'/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-gcsds_qd                                                                                                                   cwd: /tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/                                         Complete output (153 lines):                                                                                            running bdist_wheel                                                                                                     running build                                                                                                           running build_ext                                                                                                       Checking for updates from https://www.nuget.org/api/v2/.                                                                Currently running NuGet.exe 4.1.0.                                                                                      Updating NuGet.exe to 5.8.1.                                                                                            Update successful.                                                                                                      MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.                                                                                                                                                      >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<                                                                                                                                                  MSBUILD: error MSBUILD0004: Too many project files specified                                                                                                                                                                                    WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Restoring NuGet package NUnit.ConsoleRunner.3.11.1.
  Restoring NuGet package NUnit.3.12.0.
  Restoring NuGet package System.ValueTuple.4.5.0.
  Adding package 'System.ValueTuple.4.5.0' to folder '/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/packages'
  Adding package 'UnmanagedExports.1.2.7' to folder '/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/packages'
  Adding package 'NUnit.3.12.0' to folder '/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/packages'
  Adding package 'NUnit.ConsoleRunner.3.11.1' to folder '/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/packages'
  Added package 'UnmanagedExports.1.2.7' to folder '/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/packages'
  Added package 'System.ValueTuple.4.5.0' to folder '/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/packages'
  Added package 'NUnit.ConsoleRunner.3.11.1' to folder '/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/packages'
  Added package 'NUnit.3.12.0' to folder '/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/packages'

  NuGet Config files used:
      /home/pythonnet-user/.config/NuGet/NuGet.Config

  Feeds used:
      /home/pythonnet-user/.nuget/packages/
      https://api.nuget.org/v3/index.json

  Installed:
      4 package(s) to packages.config projects
  >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

  XBuild Engine Version 14.0
  Mono, Version 6.8.0.123
  Copyright (C) 2005-2013 Various Mono authors

  Build started 4/6/2021 11:39:48 AM.
  __________________________________________________
  Project "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/pythonnet.sln" (Clean target(s)):
        Target ValidateSolutionConfiguration:
                Building solution configuration "ReleaseMono|x64".
        Target Clean:
                Project "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/src/runtime/Python.Runtime.csproj" (Clean target(s)):
                        Target CoreClean:
                                Deleting file '/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/src/runtime/obj/x64/ReleaseMono/.NETFramework,Version=v4.0.AssemblyAttribute.cs'
                Done building project "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/src/runtime/Python.Runtime.csproj".
                The project 'clrmodule' is disabled for solution configuration 'ReleaseMono|x64'.
                Project "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/src/testing/Python.Test.csproj" (Clean target(s)):
                        Target CoreClean:
                                Deleting file '/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/src/testing/obj/x64/ReleaseMono/.NETFramework,Version=v4.0.AssemblyAttribute.cs'
                Done building project "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/src/testing/Python.Test.csproj".
                Project "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/src/embed_tests/Python.EmbeddingTest.csproj" (Clean target(s)):
                        Target CoreClean:
                                Deleting file '/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/src/embed_tests/obj/x64/ReleaseMono/.NETFramework,Version=v4.0.AssemblyAttribute.cs'
                Done building project "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/src/embed_tests/Python.EmbeddingTest.csproj".
                Project "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/src/console/Console.csproj" (Clean target(s)):
                        Target CoreClean:
                                Deleting file '/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/src/console/obj/x64/ReleaseMono/.NETFramework,Version=v4.0.AssemblyAttribute.cs'
                Done building project "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/src/console/Console.csproj".
  Done building project "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/pythonnet.sln".

  Build succeeded.
         0 Warning(s)
         0 Error(s)

  Time Elapsed 00:00:00.4364570

  >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

  XBuild Engine Version 14.0
  Mono, Version 6.8.0.123
  Copyright (C) 2005-2013 Various Mono authors

  Build started 4/6/2021 11:39:49 AM.
  __________________________________________________
  Project "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/pythonnet.sln" (Build target(s)):
        Target ValidateSolutionConfiguration:
                Building solution configuration "ReleaseMono|x64".
        Target Build:
                Project "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/src/runtime/Python.Runtime.csproj" (default target(s)):
                        Target PrepareForBuild:
                                Configuration: ReleaseMono Platform: x64
                                Created directory "bin/"
                        Target GenerateSatelliteAssemblies:
                        No input files were specified for target GenerateSatelliteAssemblies, skipping.
                        Target CoreCompile:
                                Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:pdbonly /optimize+ /out:obj/x64/ReleaseMono/Python.Runtime.dll /resource:obj/x64/ReleaseMono/Python.Runtime.resources.clr.py,clr.py Codecs/EncoderGroup.cs Codecs/DecoderGroup.cs Codecs/RawProxyEncoder.cs Codecs/TupleCodecs.cs converterextensions.cs finalizer.cs Properties/AssemblyInfo.cs ../SharedAssemblyInfo.cs arrayobject.cs assemblymanager.cs BorrowedReference.cs classderived.cs classbase.cs classmanager.cs classobject.cs clrobject.cs codegenerator.cs constructorbinder.cs constructorbinding.cs converter.cs CustomMarshaler.cs debughelper.cs delegatemanager.cs delegateobject.cs eventbinding.cs eventobject.cs exceptions.cs extensiontype.cs fieldobject.cs generictype.cs genericutil.cs importhook.cs indexer.cs interfaceobject.cs interfaces.cs interop.cs iterator.cs managedtype.cs metatype.cs methodbinder.cs methodbinding.cs methodobject.cs methodwrapper.cs modulefunctionobject.cs moduleobject.cs modulepropertyobject.cs nativecall.cs NewReference.cs NonCopyableAttribute.cs overload.cs propertyobject.cs pyansistring.cs pydict.cs PyExportAttribute.cs pyfloat.cs pyint.cs pyiter.cs pylist.cs pylong.cs pynumber.cs pyobject.cs pyscope.cs pysequence.cs pystring.cs pythonengine.cs pythonexception.cs pytuple.cs ReferenceExtensions.cs runtime.cs typemanager.cs typemethod.cs Util.cs platform/Types.cs platform/LibraryLoader.cs polyfill/ReflectionPolifills.cs slots/mp_length.cs interop36m.cs obj/x64/ReleaseMono/.NETFramework,Version=v4.0.AssemblyAttribute.cs /target:library /unsafe+ /define:"PYTHON36;PYTHON3;UCS4;MONO_LINUX;PYTHON_WITH_PYMALLOC" /nowarn:1591 /doc:bin/Python.Runtime.xml /langversion:7.3 /nostdlib /reference:/usr/lib/mono/4.0-api/System.dll /reference:/usr/lib/mono/4.0-api/System.Core.dll /reference:/usr/lib/mono/4.0-api//mscorlib.dll
  CSC: error CS1617: Invalid -langversion option `7.3'. It must be `ISO-1', `ISO-2', Default, Latest or value in range 1 to 7.2
                        Task "Csc" execution -- FAILED
                        Done building target "CoreCompile" in project "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/src/runtime/Python.Runtime.csproj".-- FAILED
                Done building project "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/src/runtime/Python.Runtime.csproj".-- FAILED
        Task "MSBuild" execution -- FAILED
        Done building target "Build" in project "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/pythonnet.sln".-- FAILED
  Done building project "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/pythonnet.sln".-- FAILED

  Build FAILED.
  Errors:

  /tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/pythonnet.sln (Build) ->
  (Build target) ->
  /tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/src/runtime/Python.Runtime.csproj (default targets) ->
  /usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

        CSC: error CS1617: Invalid -langversion option `7.3'. It must be `ISO-1', `ISO-2', Default, Latest or value in range 1 to 7.2

         0 Warning(s)
         1 Error(s)

  Time Elapsed 00:00:00.5292530
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/setup.py", line 659, in <module>
      zip_safe=False,
    File "/home/pythonnet-user/.venvs/kpclib/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command                                    [27/2531]      cmd_obj.run()
    File "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/setup.py", line 612, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "/home/pythonnet-user/.venvs/kpclib/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/setup.py", line 353, in build_extension
      subprocess.check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
    File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON36%3BPYTHON3%3BUCS4%3BMONO_LINUX%3BPYTHON_WITH_PYMALLOC" /p:PythonBuildDir="/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/build/lib.linux-x86_64-3.6" /p:PythonInteropFile="interop36m.cs" /p:PackageId=pythonnet_py36_x64 /verbosity:normal /t:Build' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: /home/pythonnet-user/.venvs/kpclib/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/setup.py'"'"'; __file__='"'"'/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wurdv3p9/install-record.txt --single-version-externally-managed --compile --install-headers /home/pythonnet-user/.venvs/kpclib/include/site/python3.6/pythonnet
         cwd: /tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/pythonnet-user/.venvs/kpclib/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/setup.py'"'"'; __file__='"'"'/tmp/pip-install-reytl_j9/pythonnet_8a3d75a891544712bdcbb4496557aca7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wurdv3p9/install-record.txt --single-version-externally-managed --compile --i$stall-headers /home/pythonnet-user/.venvs/kpclib/include/site/python3.6/pythonnet Check the logs for full command output.   
```

**Comment by filmor** [comment] 2021-04-06 11:51
This is not a support forum. The error seems to be a duplicate of #1223.

**Closed by filmor** 2021-04-06 11:51 UTC
