### ISSUE TITLE
Crashing IIS

### ISSUE THREAD

**Issue by wdrobinson** [pythonnet/pythonnet#515] opened 2017-07-20 20:00 UTC
### Environment

-   Pythonnet 2.3.0:
-   Python 2.7:
-   Operating System : Windows 10

### Details

-   I'm running pythonnet in a c# web service. It's occasionally (and randomly as far as I can tell) crashing IIS when I'm attempting to import a module but I can't find a reliable way to recreate the error. The only way I have of replicating the IIS crash is to set PythonEngine.PythonHome to a location where python doesn't exist and call PythonEngine.Initialize(). This will cause IIS express to exit with code 1 and I'm unable to catch the error.

**Comment by denfromufa** [comment] 2017-07-20 22:11
Can you provide full reproducible example?

**Comment by willdrob** [comment] 2017-07-21 13:22
I created a Web API project and added pythonnet. I included python 2.7 in my project so I could easily deploy to new machines without needing to install python on each. Here's some simple code for initializing python. I included this in a GET so I could easily test it:

`var path = $"{Environment.GetEnvironmentVariable("Path", EnvironmentVariableTarget.Machine)};{HostingEnvironment.ApplicationPhysicalPath}Python/Python27";
Environment.SetEnvironmentVariable("Path", path, EnvironmentVariableTarget.Process);
PythonEngine.PythonHome = $"{HostingEnvironment.ApplicationPhysicalPath}Python/Python27";
PythonEngine.Initialize();`

Changing that to a directory that doesn't exist causes IIS express to crash and no errors to be thrown:

`var path = $"{Environment.GetEnvironmentVariable("Path", EnvironmentVariableTarget.Machine)};{HostingEnvironment.ApplicationPhysicalPath}Python/XYZ";
Environment.SetEnvironmentVariable("Path", path, EnvironmentVariableTarget.Process);
PythonEngine.PythonHome = $"{HostingEnvironment.ApplicationPhysicalPath}Python/XYZ";
PythonEngine.Initialize();`

**Comment by denfromufa** [comment] 2017-08-01 06:08
@willdrob can you share your minimal app? I don't want to spend time configuring IIS.

**Comment by willdrob** [comment] 2017-08-01 15:48
Here's the [app](https://github.com/willdrob/PythonNetTestApp)

I realized it's not just an IIS issue so I created a simple console app to illustrate it. I have 64-bit python installed on my system and the above app is using the 64-bit binary and runs fine unless you remove the comment that sets `PythonEngine.PythonHome` to a directory that doesn't exist. If you do the app exits with code 1 and no error is thrown from `Python.Runtime`. If you don't have python installed at all it correctly throws an error: "Unable to load DLL 'python27'" so I'm assuming the issue is happening when it loads the python DLL and is unable to find the python install location.

**Comment by denfromufa** [comment] 2017-08-01 16:32
@willdrob so what do you expect instead of these errors from pythonnet?

**Comment by willdrob** [comment] 2017-08-01 16:48
I would expect an error from pythonnet that can be captured and handled instead of the application crashing.

**Comment by dmitriyse** [comment] 2017-09-06 23:07
Probably this issue is fixed by https://github.com/pythonnet/pythonnet/pull/535

**Comment by filmor** [comment] 2020-06-09 15:37
Since there have not been any updates in quite a while, I'll close this issue. Feel free to reopen and provide a information on the current state.

**Closed by filmor** 2020-06-09 15:37 UTC
Labels: requires review
