### ISSUE TITLE
Encoding issue. PyScope.Exec()

### ISSUE THREAD

**Issue by NickSavin** [pythonnet/pythonnet#818] opened 2019-02-18 10:52 UTC
### Environment

-  Pythonnet version: 2.4.0.dev
-   Python version: 3.7
-   Operating System: Win10

### Details

-   I have a script, represented by a string in .net side: 
` string script = "a = \"Привет\"";` 

I try to run this script, using PyScope.Exec()
```
public void ExecuteScript(string script, IDictionary<string, object> locals)
        {
            _scriptLocals = new PyDict();

            using (Py.GIL())
            {
                if (locals != null)
                    foreach (var local in locals)
                        _scriptLocals[local.Key] = local.Value.ToPython();

                using (var pythonScope = Py.CreateScope())
                {
                    pythonScope.Exec(script, _scriptLocals);
                }
            }
        }
```
When I run method pythonScope.Exec(script, _scriptLocals), I get an exception:

> SyntaxError : ("(unicode error) 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte", ('<string>', 1, 4, None))
> 

StackTrace is empty

**Comment by NickSavin** [comment] 2019-02-18 11:04
I found in source code, that **PyScope.Exec** method calls the next external method in **Runtime** class:

```
[DllImport(_PythonDll, CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr PyRun_String(string code, IntPtr st, IntPtr globals, IntPtr locals);
``` 

I added for a test a new external method at **Runtime** class:
```
 [DllImport(_PythonDll, CallingConvention = CallingConvention.Cdecl , EntryPoint = "PyRun_String")]
        internal static extern IntPtr PyRun_StringGb([MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(Utf8Marshaler))] string code, IntPtr st, IntPtr globals, IntPtr locals);
```
and a new method at PyScope class:

```
 public void ExecGb(string code, PyDict locals = null)
        {
            Check();

            IntPtr _locals = locals == null ? variables : locals.obj;

            var flag = (IntPtr)Runtime.Py_file_input;

            IntPtr ptr = Runtime.PyRun_StringGb(code, flag, variables, _locals);

            Runtime.CheckExceptionOccurred();
            if (ptr != Runtime.PyNone)
            {
                throw new PythonException();
            }
            Runtime.XDecref(ptr);
        }
```

If I use my new method  **pythonScope.ExecGb(script, _scriptLocals)**, there are no excetions, and script works fine.

But I am in doubts, is it an appropriate solution?

**Comment by denfromufa** [comment] 2019-02-21 17:38
@yagweb any idea?

**Comment by sschukat** [comment] 2019-03-05 13:30
Since the PyRun_String is defined as        
 ```
[DllImport(_PythonDll, CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr PyRun_String(string code, IntPtr st, IntPtr globals, IntPtr locals);

```
The CharSet Field is defaulted to CharSet.Ansi hence there will be an encoding with the system default, which then is decoded with UTF8 which will then cause the error. 
Since the API function is defined as  
`PyObject* PyRun_String(const char *str, int start, PyObject *globals, PyObject *locals)`
The only option is to use the correct marshalling as suggested.

**Comment by filmor** [comment] 2019-03-05 15:06
I don't think it's that simple. The decoding logic that is applied in `PyRun_String` is the same as for modules, i.e. Python tries to find a comment that specifies the encoding, and if it doesn't find one it defaults to ASCII (IIRC) for Python 2 and UTF8 for Python 3. So your fix indeed corrects things for Python 3, but only if no one puts an encoding comment in. I don't have a good answer to this, yet. For Python 3, we should probably use UTF-8 marshalling and additonally deactivate the comment processing using the (apparently undocumented) flag `PyPARSE_IGNORE_COOKIE`.

**Comment by sschukat** [comment] 2019-03-05 21:43
I agree for Python 3, since the input string from .NET is always Unicode and we would have to assume an encoding to map to the character array for the `PyRun_String` method. Here UTF8 is the best guess. 
For Python 2.7 to make it more complex, the installation could be customized to set a defaultencoding in site.py in the function `setencoding`. Hence it is not always ASCII. So the fix will only work for Python 3.
The fix (correct marshaling definition) would have to applied for other imports too, e.g. `PyRun_SimpleString`, `Py_CompileString`, `PyBytes_FromString`, ...

**Comment by filmor** [comment] 2019-03-06 11:59
Well, the functions are not available for "public consumption", so we can make them do whatever we want them to. I also would really not like to invest much time in Python 2 support on such an edge case, seeing it's going to be EOL end of this year. We should use the `PyPARSE_IGNORE_COOKIE`, though, to prevent nasty surprises. Same holds for the holder `PythonEngine` interface.

**Comment by TheCollegedude** [comment] 2020-05-29 10:29
I don't know about Cyrillic, but **ä** (0xe4) should be definitely a 1-byte character, right?
```
print("ä")
SyntaxError : ("(unicode error) 'utf-8' codec can't decode byte 0xe4 in position 0: unexpected end of data", ('<string>', 1, 6, None))

```

**Comment by filmor** [comment] 2020-05-29 12:44
`0xe4` is Latin1, everything `> 0x1f` is 2 bytes in UTF8. `0xe4` would be `0xc3 0xa4`.

**Comment by TheCollegedude** [comment] 2020-06-02 09:11
That makes sense! As I understand C# uses unicode strings and Python3 does also. 
I have a file created in notepad++ (encoding utf-8) and as soon as I use any non-ascii character, PythonEngine.Compile files with the "unicode error". The only command that can process such files is PyScope.Import (I suppose because the file contents are not processed in pythonnet)

**Comment by filmor** [comment] 2020-06-02 15:38
Well, that's not quite it. The issue is not with the marshalling as such, it's with /how/ Python's `PyRun_String` interprets things, and that is not quite trivial. As soon as we have 2.5 out, we will only be supporting Python 3 and probably just change this one to default to UTF8, but you would still be able to mess it up by adding encoding comments (like `# -*- coding: latin1 -*-`).

**Comment by TheCollegedude** [comment] 2020-06-09 14:13
I see, but I would rather take the "_ability to mess it up_" than having currently no way to achieve what I am trying to do. I wanted generate markdown but it complains about the backtick ´´´ `(unicode error) 'utf-8' codec can't decode byte 0xb4 in position 0: invalid start byte`

**Comment by filmor** [comment] 2020-06-09 14:18
The change has been merged already.

**Closed by filmor** 2020-06-09 14:18 UTC

**Comment by uipathact** [comment] 2021-01-05 16:20
The same issue is for CompileString:
 `        [DllImport(_PythonDll, CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr Py_CompileStringExFlags(string str, string file, int start, IntPtr flags, int optimize);`

Could you correct this as well so it would work with UTF8?
