### ISSUE TITLE
clr.AddReference crashes mono in Linux environment

### ISSUE THREAD

**Issue by samuthrakumar** [pythonnet/pythonnet#1306] opened 2020-12-04 01:53 UTC
### Environment

-   Pythonnet version: 2.5.1
-   Python version:  Python 3.6.12 :: Anaconda, Inc.
-   Operating System: Linux (Ubuntu 18.04.5 LTS bionic)
-   mono version : Mono JIT compiler version 6.12.0.90 

### Details

-   I am trying to add reference of .Net standard library(Linux compatible) from the python code.
import clr
clr.AddReference("xxxx.xx")

The code throws the below exception and mono crashes after that

```
*** Assertion at assembly.c:1939, condition `is_ok (hook_error)' not met, function:mono_assembly_invoke_load_hook_internal, (null) assembly:/usr/lib/mono/4.5/mscorlib.dll type:ReflectionTypeLoadException member:(null)**


=================================================================
        Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
        Native stacktrace:
=================================================================
        0x7fec3a9382a9 - /usr/lib/libmonosgen-2.0.so.1 :
        0x7fec3a938629 - /usr/lib/libmonosgen-2.0.so.1 :
        0x7fec3a8c2c94 - /usr/lib/libmonosgen-2.0.so.1 :
        0x7fec3a937842 - /usr/lib/libmonosgen-2.0.so.1 :
        0x7fec59a97980 - /lib/x86_64-linux-gnu/libpthread.so.0 :
        0x7fec596d2fb7 - /lib/x86_64-linux-gnu/libc.so.6 : gsignal
        0x7fec596d4921 - /lib/x86_64-linux-gnu/libc.so.6 : abort
        0x7fec3ab1d3a7 - /usr/lib/libmonosgen-2.0.so.1 :
        0x7fec3ab02573 - /usr/lib/libmonosgen-2.0.so.1 :
        0x7fec3ab1d328 - /usr/lib/libmonosgen-2.0.so.1 :
        0x7fec3ab1d8e3 - /usr/lib/libmonosgen-2.0.so.1 : monoeg_assertion_message
        0x7fec3a9a1b98 - /usr/lib/libmonosgen-2.0.so.1 :
        0x7fec3a9a28e7 - /usr/lib/libmonosgen-2.0.so.1 :
        0x7fec3a9a4c13 - /usr/lib/libmonosgen-2.0.so.1 :
        0x7fec3a9a43e1 - /usr/lib/libmonosgen-2.0.so.1 :
        0x7fec3a9a6351 - /usr/lib/libmonosgen-2.0.so.1 : mono_assembly_load_reference
        0x7fec3a9ae3fb - /usr/lib/libmonosgen-2.0.so.1 : mono_class_from_typeref_checked
        0x7fec3aa0430c - /usr/lib/libmonosgen-2.0.so.1 :
        0x7fec3aa045f2 - /usr/lib/libmonosgen-2.0.so.1 :
        0x7fec3aa9364f - /usr/lib/libmonosgen-2.0.so.1 :
        0x7fec3aa942e8 - /usr/lib/libmonosgen-2.0.so.1 :
        0x7fec3aa949e8 - /usr/lib/libmonosgen-2.0.so.1 :
        0x7fec3a9e8dfe - /usr/lib/libmonosgen-2.0.so.1 :
        0x41cb3773 - Unknown
```

```python
import clr
clr.AddReference("LiveAI.SDK")
```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by filmor** [comment] 2020-12-04 05:27
Can you please verify that this library can be loaded by a normal C# program? This doesn't look like an error specific to Python.NET.

**Comment by samuthrakumar** [comment] 2020-12-04 17:49
yes, I can load the same assembly using the c# program on the same Linux platform

![image](https://user-images.githubusercontent.com/11955837/101196677-e9d20380-3615-11eb-8d6f-228462d5c4dc.png)

**Comment by filmor** [comment] 2020-12-04 21:45
Then I'd need a copy of the DLL in questio n to run the import in the debugger.

**Comment by samuthrakumar** [comment] 2020-12-05 02:25
The crash happens only when I try to load the .net standard binary. It works fine with the .net framework. I have attached a test library with this and try the below code.

import clr
clr.AddReference("TestLibrary1")
import TestLibrary as testLibrary
lib = testLibrary.TestClass()
print(lib.Method())
[netstandard2.0.zip](https://github.com/pythonnet/pythonnet/files/5646344/netstandard2.0.zip)

**Comment by filmor** [comment] 2020-12-05 11:07
Works fine for me with current master and Mono 6.10.

**Comment by samuthrakumar** [comment] 2020-12-07 01:19
Thanks Filmor for trying.. I hope you have tried it in **Linux machine.** The code works fine in windows, I see the issue on my Linux (Ubuntu 18.04.5 LTS bionic) environment (Python 3.6.12 ). 

Here are the steps I followed :

- apt install gnupg ca-certificates
- apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
- echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
- apt install mono-complete 
- clang (sudo apt-get install clang)
- glib (sudo apt-get install libglib2.0-dev)

Installed Pythonnet using
   pip install  pythonnet==2.5.1 (also tried pip install git+git://github.com/pythonnet/pythonnet.git)

import clr
clr.AddReference(".net standard 2.0 library") -> **Mono crashes**
clr.AddReference(".net framework 4.7 library") -> Works fine.

Any help would be appreciated.

**Comment by RafeusFox** [comment] 2020-12-07 02:21
I got the same problem on Ubuntu 20.04.1 LTS (Focal Fossa).
I have installed mono following the instructions from here:
https://linuxize.com/post/how-to-install-mono-on-ubuntu-18-04/
I have installed Pythonnet using pip3.

For instance, my python code is:
```
import clr, sys
    if __name__ == '__main__':
        sys.path = ['/usr/lib/mono/4.5', '/usr/local/lib/dwsim']
        clr.AddReference('DWSIM.Interfaces')
        clr.AddReference('DWSIM.Automation')
        from DWSIM import Interfaces, Automation
        process = Automation.Automation2() # Crash
```
When I run it on Windows everything works fine.
But on Linux it leads to crash.

Similar code in C#:
```
using System;
using DWSIM.Automation;
using DWSIM.Interfaces;

namespace DWSIM_test { 
        class MainClass {
            public static void Main(string[] args) {
                var Automation = new DWSIM.Automation.Automation2();
                }
            }
        }
```
works fine for both Windows and Linux.
- Mono JIT compiler version 6.12.0.90
- Python version 3.8.5
- Pythonnet version 2.5.1

What could be wrong?

**Comment by filmor** [comment] 2020-12-07 07:00
I tried this with the example library on Gentoo, I'll see how it behaves in an Ubuntu container.

**Comment by filmor** [comment] 2020-12-07 17:06
Sorry, works completely fine as well for me on a fresh install in an Ubuntu Docker container...

I'll keep this one open for a while, but there is no point in keeping it without a reproducible example.

**Comment by samuthrakumar** [comment] 2020-12-10 05:46
@filmor,  when I dig deeper into the issue, I see clr.addreference loads the .net standard assembly fine and execute fine for most of the code. But I see the crash happens when I add some Microsoft NuGet packages like Azure.Storage.Blobs and execute related code using those NuGet binaries. Is there anything I should do for executing .net core/ .Net standard (self-contained) binaries?

In the below code, everything works fine if I create binary with only step 1. But the crash happens when I add the code for step 2

using Azure.Storage.Blobs; //used for step 2
using Newtonsoft.Json.Linq;
using System;

namespace LinuxEnvironmentTest
{
    public class TestClass
    {
        public bool Method()
        {
            /* step 1 */
            Console.WriteLine(".Net standard 2.0");

            JArray array = new JArray();
            array.Add("Manual text");
            array.Add(new DateTime(2000, 5, 23));

            JObject o = new JObject();
            o["MyArray"] = array;

            string json = o.ToString();
            Console.WriteLine(json);

            **/* step 2 */
            BlobContainerClient container = new BlobContainerClient("****connectionstring****", "code");
            Console.WriteLine(container.Exists());**
            return true;
        }
    }
}

**Comment by filmor** [comment] 2020-12-10 17:35
That's a completely different case. Also, your test-case again works completely fine for me (just errors out with a proper exception because of the connection string). I'll close this issue, feel free to reopen it once you have a reproducible example (e.g. try to build a Dockerfile that reproduces the error).

**Closed by filmor** 2020-12-10 17:35 UTC

**Comment by vnavkal** [comment] 2021-01-14 02:40
@filmor I believe I've managed to reproduce this error as well.  I posted a dockerfile in https://github.com/vnavkal/pythonnet-ex that compiles similar code to what @samuthrakumar posted and then attempts to import it via pythonnet.  And when I run the image, I see a similar cryptic crash log.

It's not clear to me whether the issue is with pythonnet or with mono.  I'm happy to try further debugging steps to pin down the source of the issue further, just let me know.

Thanks in advance!

**Comment by vnavkal** [comment] 2021-01-14 15:59
Actually, perhaps the reason why my example caused mono to crash is that I built my project to target .NET core (https://github.com/vnavkal/pythonnet-ex/blob/3f5166fb6636ace676d4c5c761ed09fd30670a42/ExampleProject.csproj#L5), and I see in #984 that importing .NET core libraries into python is not fully supported.  When I switch the target framework to `netstandard2.1`, I'm able to invoke the .NET code from within python.

**Comment by MysterTech** [comment] 2021-01-20 05:56
Thanks vnavkal for decrypting this for me. I got the same error while building the QuantConnect lean indicators into my python project.

**Comment by Cuky88** [comment] 2022-03-10 12:35
> Thanks @vnavkal for decrypting this for me. I got the same error while building the QuantConnect lean indicators into my python project.

How did you fix that? I have the same problems with QuantConnect.Visualizer.py. Changing <TargetFramework> to "netstandard2.1" in QuantConnect.ToolBox.csproj does not work, the other Lean projects fail to build since they use "net5.0" as default.

**Comment by alexchen-vm** [comment] 2022-10-11 02:26
Got the same error on centos7 with mono 6.12.0.107.
My app is using .NET assemblies 4.0.0.0, which then reference to a nuget package which then reference System.Text.Json.dll 5.0.0.0. AddRefrence("System.Text.Json.dll") caused the crash. 
The same app works fine on Mono 6.10.0 and 6.8.0. pythonnet version is 3.0.0.post1
Reproduce steps:
1) Find System.Text.Json.dll 5.0.0.0
2) Run the following code
import clr
clr.AddReference("System.Text.Json.dll")
[System.Text.Json.zip](https://github.com/pythonnet/pythonnet/files/9750491/System.Text.Json.zip)

**Comment by applepi-icpc** [comment] 2023-12-09 05:12
> Got the same error on centos7 with mono 6.12.0.107. My app is using .NET assemblies 4.0.0.0, which then reference to a nuget package which then reference System.Text.Json.dll 5.0.0.0. AddRefrence("System.Text.Json.dll") caused the crash. The same app works fine on Mono 6.10.0 and 6.8.0. pythonnet version is 3.0.0.post1 Reproduce steps:
> 
> 1. Find System.Text.Json.dll 5.0.0.0
> 2. Run the following code
>    import clr
>    clr.AddReference("System.Text.Json.dll")
>    [System.Text.Json.zip](https://github.com/pythonnet/pythonnet/files/9750491/System.Text.Json.zip)

You saved my day! I switched my mono version from 6.12.0.199 to 6.10.0.104 and my problem was gone. Thank you!
