### ISSUE TITLE
cannot get anymore int of enumclass (alpha2)

### ISSUE THREAD

**Issue by maxcapodi78** [pythonnet/pythonnet#1810] opened 2022-06-08 14:00 UTC
### Environment

-   Pythonnet version: 3.0.0dev
-   Python version: 3.9
-   Operating System: Windows
-   .NET Runtime:

### Details

-   Describe what you were trying to get done.

In v2.5.2 I'm able to get a C# enum and get the int value. In alpha 2 it seems that the full enum class is returned but the int command is not working. In 3.0.0dev it makes crashing the Debugger.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.
![image](https://user-images.githubusercontent.com/77293250/172635930-3f5d51aa-3989-410f-9189-12570843135c.png)

-   If there was a crash, please include the traceback here.

```python
    Out[13]: <bound method 'int'>

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at Python.Runtime.Runtime.PyLong_FromLongLong(Int64 value)
at Python.Runtime.PyInt..ctor(Int64 value)
at Python.Runtime.EnumOps`1.int(T value)
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Python.Runtime.MethodBinder.Invoke(BorrowedReference inst, BorrowedReference args, BorrowedReference kw, MethodBase info, MethodBase[] methodinfo)
at Python.Runtime.MethodObject.Invoke(BorrowedReference target, BorrowedReference args, BorrowedReference kw, MethodBase info)
at Python.Runtime.MethodBinding.tp_call(BorrowedReference ob, BorrowedReference args, BorrowedReference kw)

Process finished with exit code -532462766
```

**Comment by filmor** [comment] 2022-06-08 14:09
I can't reproduce this, you have given almost no code here. Does the code run outside of the debugger? Please provide a Minimal, Complete and Verifiable example.

**Comment by maxcapodi78** [comment] 2022-06-08 14:39
Hi @filmor I don't know how to create an example for you since I obtain it from My C# API that returns an enum on the following call: 
 self.edbcomponent.GetComponentType()

I have the full enum in it including .value__ property (not .value). When I do the int of that enum it crashes and and stops to work. It fails also in running mode.
This is the content of the enum 
![image](https://user-images.githubusercontent.com/77293250/172644573-3a48dfde-277c-4db5-9c73-15481ca2a6e0.png)
the command should return 1 (the content of value__)

**Comment by filmor** [comment] 2022-06-08 14:42
I am sorry, I can't and won't do remote debugging. Please provide a complete example that reproduces the issue that I can run on my machine.

**Comment by filmor** [comment] 2022-06-08 15:01
Odd that this works in the unit test itself, I'll have a look.

**Comment by maxcapodi78** [comment] 2022-06-08 15:27
@filmor I've taken from UT the enum to test but I noticed that you don't run a test on an enum value.
So you can debug and add that as additional test for future reference

**Comment by lostmsu** [comment] 2022-06-08 18:14
The exception looks like GIL is being released somewhere.

**Comment by filmor** [comment] 2022-06-13 13:34
@maxcapodi78 This should be fixed on the current master, if not, please reopen :)

**Closed by filmor** 2022-06-13 13:34 UTC
