### ISSUE TITLE
how to avoid runtime error R6034 with C Runtime (MSVCR) on Windows

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#89] opened 2015-08-15 16:42 UTC
This problem appears with Python installation from Anaconda distribution.
More details here:

https://github.com/ContinuumIO/anaconda-issues/issues/410

How to avoid this problem when CPython embedded in PythonNET?
Seems that others hit this problem too:

http://code.activestate.com/lists/pythondotnet/1602/

**Comment by tonyroberts** [comment] 2015-08-17 08:34
You have to include the C runtime version in your application manifest, something like this:

```
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"></requestedExecutionLevel>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="win32" name="Microsoft.VC90.CRT" version="9.0.21022.8" processorArchitecture="amd64" publicKeyToken="1fc8b3b9a1e18e3b"></assemblyIdentity>
    </dependentAssembly>
  </dependency>
</assembly>
```

You can extract the manifest from python.exe to get the right version for the build of Python you're using.

It's not enough for this to be in the python.dll manifest, it has to be in your application manifest.

**Comment by denfromufa** [comment] 2015-08-18 20:06
What if the application still throws runtime error? BTW, the VRT runtime version in Anaconda folder does not match the runtime in the manifest file extracted from Python.exe.
Also I have multiple layers before python is embedded: exe -> com -> .NET -> CPython embedded

**Comment by tonyroberts** [comment] 2015-08-19 08:42
Sounds like possibly an anaconda packaging problem if the versions don't match.

What determines how the c runtime is loaded is the current activation context. Usually that is set up according to the executable's manifest, but if you have several layers of stuff then you will need to understand how each one of those is affecting the activation context prior to the python dll being loaded.

See https://msdn.microsoft.com/en-us/library/aa374153(v=vs.85).aspx for more information on activation contexts.

One approach could be to create your own activation context using the manifest from python27.dll before loading python. Another would be to build all the various components of your application using the same c runtime.

Before you do that though, you might want to try a different Python distribution to see if it is just a problem with that specific anaconda distribution (and if it is I'm sure they will be able to fix it if you can report exactly what the problem is). FWIW I've been able to embed python into various applications using the distribution from python.org, as well as by building it from source.

**Comment by denfromufa** [comment] 2015-08-19 15:57
yes, I do not have this problem on official CPython. Anaconda is convenient for new VMs, but I may have to move away due to this issue with CRT. At least conda is good enough :)

Activation context seems pretty complicated to implement.

It looks like like another manifest file is required in the same folder:

 Microsoft.VCXX.CRT.manifest 
http://www.codeproject.com/Tips/211756/How-to-Distribute-C-run-time-CRT-Libraries-with-Yo

**Comment by tonyroberts** [comment] 2015-08-25 09:33
I'm going to close this since it doesn't appear to be a pythonnet problem but rather an anaconda problem.

**Closed by tonyroberts** 2015-08-25 09:33 UTC

**Comment by denfromufa** [comment] 2015-08-25 15:03
Agreed

**Comment by denfromufa** [comment] 2016-01-28 05:18
BTW, this is now resolved by installing/uninstalling `msvc_runtime` using conda in *conda environments

**Comment by huanfachen** [comment] 2019-04-29 19:29
This works for me! Thanks @denfromufa 

Execute the following command (outside of any conda env):

conda install mscv_runtime

**Comment by geosconsulting** [comment] 2019-07-14 09:24
conda install mscv_runtime
is in reality
conda install ms**vc**_runtime
