### ISSUE TITLE
Can't install on Ubuntu 16.04

### ISSUE THREAD

**Issue by aushani** [pythonnet/pythonnet#654] opened 2018-04-03 15:34 UTC
### Environment

-   Pythonnet version: master and 2.3.0
-   Python version: 2.7.12
-   Operating System: Ubuntu 16.04

### Details

Trying to install using pip, I get the following errors for master and 2.3.0

```
$ pip install git+https://github.com/pythonnet/pythonnet
Collecting git+https://github.com/pythonnet/pythonnet
  Cloning https://github.com/pythonnet/pythonnet to /tmp/pip-jY3N1G-build
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-jY3N1G-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Xvwc8d-record/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --single-version-externally-managed not recognized
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-jY3N1G-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Xvwc8d-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-jY3N1G-build/
``````

And

```
$ sudo -H pip install pythonnet
Collecting pythonnet
  Using cached pythonnet-2.3.0.tar.gz
Building wheels for collected packages: pythonnet
  Running setup.py bdist_wheel for pythonnet ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2paJ4D/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpAYPkUUpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 3.5.0.
  Updating NuGet.exe to 4.5.1.
  Update successful.
  MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.
  Restoring NuGet package NUnit.3.6.0.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Restoring NuGet package NUnit.ConsoleRunner.3.6.0.
  Adding package 'NUnit.3.6.0' to folder '/tmp/pip-build-2paJ4D/pythonnet/packages'
  Adding package 'UnmanagedExports.1.2.7' to folder '/tmp/pip-build-2paJ4D/pythonnet/packages'
  Adding package 'NUnit.ConsoleRunner.3.6.0' to folder '/tmp/pip-build-2paJ4D/pythonnet/packages'
  Added package 'UnmanagedExports.1.2.7' to folder '/tmp/pip-build-2paJ4D/pythonnet/packages'
  Added package 'NUnit.ConsoleRunner.3.6.0' to folder '/tmp/pip-build-2paJ4D/pythonnet/packages'
  Added package 'NUnit.3.6.0' to folder '/tmp/pip-build-2paJ4D/pythonnet/packages'
  
  NuGet Config files used:
      /root/.config/NuGet/NuGet.Config
  
  Feeds used:
      /root/.nuget/packages/
      https://api.nuget.org/v3/index.json
  
  Installed:
      3 package(s) to packages.config projects
  
  >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
  
  XBuild Engine Version 14.0
  Mono, Version 5.10.1.20
  Copyright (C) 2005-2013 Various Mono authors
  
  >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
  
  XBuild Engine Version 14.0
  Mono, Version 5.10.1.20
  Copyright (C) 2005-2013 Various Mono authors
  		Configuration: ReleaseMono Platform: x64
  /tmp/pip-build-2paJ4D/pythonnet/src/runtime/Python.Runtime.csproj: error : Error executing task Copy: Error converting Property named 'SourceFiles' with value '$(TargetAssemblyPdb)' to type Microsoft.Build.Framework.ITaskItem[]: Can't concatenate Item list with other strings where an item list is expected ('@(_OutDirItem->'%(FullPath)')', 'Python.Runtime.pdb'). Use semi colon to separate items.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-2paJ4D/pythonnet/setup.py", line 405, in <module>
      zip_safe=False,
    File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/lib/python2.7/distutils/command/build_ext.py", line 448, in build_extensions
      self.build_extension(ext)
    File "/tmp/pip-build-2paJ4D/pythonnet/setup.py", line 222, in build_extension
      subprocess.check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
    File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON27,PYTHON2,UCS4,MONO_LINUX,PYTHON_WITHOUT_ENABLE_SHARED" /p:PythonBuildDir="/tmp/pip-build-2paJ4D/pythonnet/build/lib.linux-x86_64-2.7" /p:PythonInteropFile="interop27.cs" /verbosity:minimal /t:Build' returned non-zero exit status 1
  
  ----------------------------------------
  Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2paJ4D/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-e6eIuH-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    Checking for updates from https://www.nuget.org/api/v2/.
    Currently running NuGet.exe 4.5.1.
    NuGet.exe is up to date.
    MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.
    All packages listed in packages.config are already installed.
    
    >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
    
    XBuild Engine Version 14.0
    Mono, Version 5.10.1.20
    Copyright (C) 2005-2013 Various Mono authors
    
    >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
    
    XBuild Engine Version 14.0
    Mono, Version 5.10.1.20
    Copyright (C) 2005-2013 Various Mono authors
    		Configuration: ReleaseMono Platform: x64
    /tmp/pip-build-2paJ4D/pythonnet/src/runtime/Python.Runtime.csproj: error : Error executing task Copy: Error converting Property named 'SourceFiles' with value '$(TargetAssemblyPdb)' to type Microsoft.Build.Framework.ITaskItem[]: Can't concatenate Item list with other strings where an item list is expected ('@(_OutDirItem->'%(FullPath)')', 'Python.Runtime.pdb'). Use semi colon to separate items.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2paJ4D/pythonnet/setup.py", line 405, in <module>
        zip_safe=False,
      File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 448, in build_extensions
        self.build_extension(ext)
      File "/tmp/pip-build-2paJ4D/pythonnet/setup.py", line 222, in build_extension
        subprocess.check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON27,PYTHON2,UCS4,MONO_LINUX,PYTHON_WITHOUT_ENABLE_SHARED" /p:PythonBuildDir="/tmp/pip-build-2paJ4D/pythonnet/build/lib.linux-x86_64-2.7" /p:PythonInteropFile="interop27.cs" /verbosity:minimal /t:Build' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2paJ4D/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-e6eIuH-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-2paJ4D/pythonnet/

**Comment by aushani** [comment] 2018-04-03 16:52
My environment really isn't anything special. It's just your standard Ubuntu 16.04. What are my options?

**Comment by dmitriyse** [comment] 2018-04-03 16:53
Please  try to install from the https://github.com/pythonnet/pythonnet/tree/featured branch
Otherwise somebody from the core team should try to reproduce your problem

**Comment by aushani** [comment] 2018-04-03 17:03
How do I install from that branch?

**Comment by denfromufa** [comment] 2018-04-03 18:00
@aushani see the wiki for installation, this issue above maybe due to mono version. try this version used in travis ci - mono 5.10.0.140-0xamarin1+ubuntu1404b1:

https://travis-ci.org/pythonnet/pythonnet/jobs/348038386#L637

**Comment by denfromufa** [comment] 2018-04-05 02:41
related: https://mail.python.org/pipermail/pythondotnet/2018-April/001958.html

**Comment by denfromufa** [comment] 2018-06-06 14:51
@u01ai11 are you sure about Python 2.3?!

**Comment by arisliang** [comment] 2018-07-27 16:18
I couldn't install for python 3.6 on ubuntu 16.04 as well. Running `pip install pythonnet` gives:
> Failed building wheel for pythonnet

**Comment by se-l** [comment] 2018-07-29 04:20
facing the same issue referencing here some other issue reports and threads which make me look more into setuptools and disutils. could downgrading specific packages help??

[https://github.com/rtfd/readthedocs.org/issues/1843]
[https://github.com/pypa/pip/issues/3698]

**Comment by arisliang** [comment] 2018-07-29 09:12
my pip version is 18.0, and setuptools is 39.1.0. Any particular package needs to downgrade to what version?

**Comment by denfromufa** [comment] 2018-08-08 18:59
@arisliang i thought i replied to this, you are missing clang, see this line in your error traceback:

`FileNotFoundError: [Errno 2] No such file or directory: 'clang': 'clang'`

**Comment by denfromufa** [comment] 2018-08-23 21:47
Ubuntu Xenial is going to be supported for Python 3.7 as part of this PR once completed:

https://github.com/pythonnet/pythonnet/pull/698

**Comment by arisliang** [comment] 2018-08-25 02:47
Will it work for Python 3.6?

**Comment by denfromufa** [comment] 2018-08-27 02:45
@arisliang it should

**Comment by denfromufa** [comment] 2018-12-10 03:02
Not sure if this is still an issue, closing for now. Please report back otherwise. Python 3.7 with Ubuntu Xenial 16.04 is merged.

**Closed by denfromufa** 2018-12-10 03:02 UTC

**Comment by jamjury** [comment] 2018-12-10 12:22
Still an issue.

Pythonnet: 2.3.0
Python: 3.7.1
Operating System: Windows 10

```
C:\Program Files (x86)\Python37-32\Scripts>pip install pythonnet
Collecting pythonnet
  Using cached https://files.pythonhosted.org/packages/89/3b/a22cd45b591d6cf490ee8b24d52b9db1f30b4b478b64a9b231c53474731e/pythonnet-2.3.0.tar.gz
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... error
    Complete output from command "c:\program files (x86)\python37-32\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\Peter\\AppData\\Local\\Temp\\pip-install-a5bxshg9\\pythonnet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Peter\AppData\Local\Temp\pip-record-lmnq9b87\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    Џа®ўҐаЄ  ®Ў­®ў«Ґ­Ё© Ё§ "https://www.nuget.org/api/v2/".
    ‘Ґ©з б § ЇгйҐ­ NuGet.exe 3.5.0.
    ЋЎ­®ў«Ґ­ЁҐ NuGet.exe ў 4.7.1.
    ЋЎ­®ў«Ґ­ЁҐ ўлЇ®«­Ґ­®.
    MSBuild auto-detection: using msbuild version '15.9.20.62856' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.
    Restoring NuGet package NUnit.3.6.0.
    Restoring NuGet package NUnit.ConsoleRunner.3.6.0.
    Restoring NuGet package UnmanagedExports.1.2.7.
    Adding package 'NUnit.ConsoleRunner.3.6.0' to folder 'C:\Users\Peter\AppData\Local\Temp\pip-install-a5bxshg9\pythonnet\packages'
    Adding package 'NUnit.3.6.0' to folder 'C:\Users\Peter\AppData\Local\Temp\pip-install-a5bxshg9\pythonnet\packages'
    Adding package 'UnmanagedExports.1.2.7' to folder 'C:\Users\Peter\AppData\Local\Temp\pip-install-a5bxshg9\pythonnet\packages'
    Added package 'UnmanagedExports.1.2.7' to folder 'C:\Users\Peter\AppData\Local\Temp\pip-install-a5bxshg9\pythonnet\packages'
    Added package 'NUnit.ConsoleRunner.3.6.0' to folder 'C:\Users\Peter\AppData\Local\Temp\pip-install-a5bxshg9\pythonnet\packages'
    Added package 'NUnit.3.6.0' to folder 'C:\Users\Peter\AppData\Local\Temp\pip-install-a5bxshg9\pythonnet\packages'

    NuGet Config files used:
        C:\Users\Peter\AppData\Roaming\NuGet\NuGet.Config
        C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

    Feeds used:
        C:\Users\Peter\.nuget\packages\
        https://api.nuget.org/v3/index.json
        C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

    Installed:
        3 package(s) to packages.config projects
    Traceback (most recent call last):
      File "tools\geninterop\geninterop.py", line 292, in <module>
        sys.exit(main())
      File "tools\geninterop\geninterop.py", line 272, in main
        python_h = preprocess_python_headers()
      File "tools\geninterop\geninterop.py", line 192, in preprocess_python_headers
        for line in _check_output(cmd).splitlines():
      File "tools\geninterop\geninterop.py", line 41, in _check_output
        output = subprocess.check_output(*args, **kwargs)
      File "c:\program files (x86)\python37-32\lib\subprocess.py", line 389, in check_output
        **kwargs).stdout
      File "c:\program files (x86)\python37-32\lib\subprocess.py", line 466, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\program files (x86)\python37-32\lib\subprocess.py", line 769, in __init__
        restore_signals, start_new_session)
      File "c:\program files (x86)\python37-32\lib\subprocess.py", line 1172, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] Не удается найти указанный файл
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Peter\AppData\Local\Temp\pip-install-a5bxshg9\pythonnet\setup.py", line 405, in <module>
        zip_safe=False,
      File "c:\program files (x86)\python37-32\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\program files (x86)\python37-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\program files (x86)\python37-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\program files (x86)\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\program files (x86)\python37-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\program files (x86)\python37-32\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\program files (x86)\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files (x86)\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\program files (x86)\python37-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\program files (x86)\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files (x86)\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\program files (x86)\python37-32\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "c:\program files (x86)\python37-32\lib\distutils\command\build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "c:\program files (x86)\python37-32\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\Peter\AppData\Local\Temp\pip-install-a5bxshg9\pythonnet\setup.py", line 191, in build_extension
        subprocess.check_call([sys.executable, geninterop, interop_file])
      File "c:\program files (x86)\python37-32\lib\subprocess.py", line 341, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\program files (x86)\\python37-32\\python.exe', 'tools\\geninterop\\geninterop.py', 'src\\runtime\\interop37.cs']' returned non-zero exit status 1.

    ----------------------------------------
Command ""c:\program files (x86)\python37-32\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\Peter\\AppData\\Local\\Temp\\pip-install-a5bxshg9\\pythonnet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Peter\AppData\Local\Temp\pip-record-lmnq9b87\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Peter\AppData\Local\Temp\pip-install-a5bxshg9\pythonnet\
```

**Comment by denfromufa** [comment] 2018-12-10 12:33
There is no PYPI release yet, install from master branch:

https://github.com/pythonnet/pythonnet/wiki/Installation
