### ISSUE TITLE
Crash in Python 3.9

### ISSUE THREAD

**Issue by ksrangarajan** [pythonnet/pythonnet#1499] opened 2021-07-29 13:15 UTC
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.9
-   Operating System: WIndows Server 2012
-   .NET Runtime: .NET Framework 4.6.1

### Details

-   Describe what you were trying to get done.

    Trying to execute Python Test Script in sequence using the code of https://github.com/pythonnet/pythonnet/blob/master/src/console/pythonconsole.cs

-   What commands did you run to trigger this issue? If you can provide a
We use the code implementation of https://github.com/pythonnet/pythonnet/blob/master/src/console/pythonconsole.cs to execute the Python scripts.  Although in the Runtime.Py_Main it is said to explicitly use GIL we used the C# as it is.

-   If there was a crash, please include the traceback here.
We face random error on execution stating that 
"The thread to read or write to a virtual address for which it doesnt have appropriate access"
Also in Event viewer the faulting dll is "C:\Windows\System32\UCRTbase.dll

**Comment by magnusjjj** [comment] 2021-07-30 10:26
I don't know why my comments here were deleted, but hey.

I did a *lot* of testing with this.

the way I resolved it:
- Uninstalled the nuget package
- Checked where python's dll resided, in this case C:\Users\Tuxie\AppData\Local\Programs\Python\Python38\Lib\site-packages (i tried 3.9, had the same issue)
- Added that as a reference, along with Microsoft.CSharp that for some reason got removed as a reference when uninstalling the nuget package

All the crashes, gone. There is something wonky with threading, in that if a thread is started inside of python, it crashes upon reloading the same module after a shutdown / init combo.
The python package version is 2.5.2

**Comment by filmor** [comment] 2021-08-01 20:58
I'm not sure which comments you mean, I can't see any deleted ones. Did you maybe comment on a different issue? @ksrangarajan Can you reproduce this in a debugger?

**Comment by magnusjjj** [comment] 2021-08-02 08:43
Turns out I did, in fact, comment on a duplicate issue :').

**Comment by ksrangarajan** [comment] 2021-08-02 12:44
@filmor  It doesnt have the stack on to display. Is there any options available to enable the DEBUG mode to print detailed flow of code?

**Comment by filmor** [comment] 2021-08-05 13:32
What I mean is starting python.exe in Visual Studio's debugger. In any case, I just saw that you are using version 2.5.1, we don't support Python 3.9 in that one. At the very least you'll need to update to 2.5.2. We already have a few more tickets on crashes with 3.9, so I'll close this one. Feel free to reopen if you can pinpoint the issue.

**Closed by filmor** 2021-08-05 13:32 UTC

**Comment by magnusjjj** [comment] 2021-08-05 13:46
Can you add a reference to the main issue you are not closing? :)
