### ISSUE TITLE
Long file path support in .Net through pythonnet

### ISSUE THREAD

**Issue by Pierre-M-A-Henry** [pythonnet/pythonnet#2103] opened 2023-02-16 11:01 UTC
### Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.11
-   Operating System: Windows 10 Entreprise
-   .NET Runtime: Framework 4.8

### Details

Hello,
We have a .Net Framework API (which is a collection of dlls) that is used by our customers through Python using pythonnet. Our .Net application is files based, and file paths are passed from Python to .Net, and .Net then opens and manipulates the files.

When using a .Net Framework exe client (no python involved), we are able to open files with long file paths (> 260 characters), either by making our exe longPathAware, or by using the \\\\?\ prefix.

However we cannot get this to work when calling our dlls from python using pythonnet. I understand that python.exe is itself longPathAware (since python 3.6), but using long paths does not seem to work, with or without the \\\\?\ prefix. Once in the .Net world, functions such as File.Exists would return false.

Would there be any difference in the .net runtime as loaded by pythonnet vs a .net framework exe that might explain this difference?

Many thanks for your help
Pierre Henry

**Comment by lostmsu** [comment] 2023-05-05 04:45
Not a bug. Duplicate of https://github.com/pythonnet/pythonnet/issues/1754

**Closed by lostmsu** 2023-05-05 04:45 UTC
