### ISSUE TITLE
Pythonnet 3 Python Package

### ISSUE THREAD

**Issue by richard-gemmell-42** [pythonnet/pythonnet#1513] opened 2021-08-06 16:11 UTC
Hi,

We've got a PyPi package that depends on Pythonnet 3. It's working beautifully with 3.0.0.dev1. Thanks for all the effort you've put in.

At the moment, our users are forced to build Pythonnet from source. That's quite a struggle for some of them.

Please can you release a version of Pythonnet 3 to PyPi so our package can depend on it.

thanks very much,
Richard

**Comment by filmor** [comment] 2021-08-09 10:13
Duplicate of #1387.

We haven't planned for an actual release candidate, yet (there are still a few nasty known bugs), but we could just cut the current version as an "alpha1". @lostmsu thoughts?

**Comment by richard-gemmell-42** [comment] 2021-08-09 10:22
An alpha release would be fine.

(I'm assuming we can add a dependency to an alpha in the install_requires list of our setup.py. Even if we can't, a pre-built version is better than one our users have to compile.)

**Comment by lostmsu** [comment] 2021-08-09 16:21
@filmor I am not familiar with distribution to PyPi. Previews on NuGet work pretty well for some people, judging by downloads.

**Comment by filmor** [comment] 2021-08-09 18:08
I'll cut the current version as `alpha1` manually tomorrow. For the future, I'll see if I can finally set up weekly deployments of the wheels.

**Comment by lostmsu** [comment] 2021-08-09 18:10
Weekly is too often. I've got monthly NuGet deployments, and forgot to approve them for a few weeks last time. Nobody complained :-D

**Comment by richard-gemmell-42** [comment] 2021-08-16 08:08
@filmor Did you make an alpha release?

**Comment by Livius90** [comment] 2021-08-28 10:20
> Duplicate of #1387.
> 
> We haven't planned for an actual release candidate, yet (there are still a few nasty known bugs), but we could just cut the current version as an "alpha1". @lostmsu thoughts?

But please, when you will do that planning?

The latest release was in 2021 February, it was quite a long time ago. Pythonnet 3.x preview in NuGet have many new and different things and as i am developer i realy like to use the new version because it is better and i want to avoid any later code-refactoring for Pythonnet 2 to 3 version changing/porting. So i can do my developing based on Pythonnet 3.x preview but only for a limited developing time and it is not accaptable to use forever. Really need a strong date to get a full released pythonnet 3 because every professional developer want to provide their own SW releases from a full-released dependency packages, only.

**Comment by richard-gemmell-42** [comment] 2021-09-21 16:55
Is there any progress on this?

**Comment by pbregener** [comment] 2021-09-30 10:38
Hi @lostmsu! As you added the 3.0.0 milestone to this: Is there some progress? (Do you even have a preliminary plan/date/schedule for that milestone?)

**Comment by filmor** [comment] 2021-11-19 13:47
I have published the current `master` version as alpha1 to pypi.

**Comment by richard-gemmell-42** [comment] 2021-11-19 15:43
Thanks very much @filmor. I'll give it a try next week.

**Closed** 2021-12-22 09:29 UTC
