### ISSUE TITLE
installing pythonnet on Mac Sierra 

### ISSUE THREAD

**Issue by riccardodelutio** [pythonnet/pythonnet#465] opened 2017-05-14 11:44 UTC
I'm trying to use pythonnet in order to import a DLL assembly and use it in python. I've seen in some other threads that some people got it working. But when I try to use it I get 

`>>> import clr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/riccardodelutio/anaconda2/lib/python2.7/site-packages/clr.so, 2): Library not loaded: /usr/local/opt/glib/lib/libglib-2.0.0.dylib
  Referenced from: /Users/riccardodelutio/anaconda2/lib/python2.7/site-packages/clr.so
  Reason: image not found`

I've seen the thread #120 proposed a patch but I'm not sure if that will fix my problem.

Thank you!

**Comment by denfromufa** [comment] 2017-05-14 18:28
This looks different issue. Can you describe all steps that you did to get pythonnet installed?

**Comment by denfromufa** [comment] 2017-05-14 18:30
@spichardo @mateuszlewko @fractus did you have this issue on mac?

**Comment by mateuszlewko** [comment] 2017-05-14 19:02
Yes and I haven't tried it on different OS.

**Comment by spichardo** [comment] 2017-05-14 19:06
I haven't seen this issue. As side note I switched to Enthought Canopy instead of Anaconda (for different reasons), pythonnet 2.3.0 works out of the box with `pip install pythonnet`. I used brew to install mono.

I've been using a lot pythonnet  recently on Mac OS (Sierra) in my applications, so I know it works.

@riccardodelutio It looks the error more related to the mono installation. How was it installed?

**Comment by fractus** [comment] 2017-05-14 20:11
No, I didn't have that issue. Looking at the above though, I would proceed as follows:

* Check that `which python` points to your Anaconda installation; if not, update your user path in `.bash_profile`, restart the terminal, and try again

* If `clr.so` exists, add the following link (point to your mono installation) and try again.
```
vasilios@exumas: /usr/local/anaconda/lib
└─ $ ll | grep mono
lrwxr-xr-x    1 vasilios  staff    60B 14 May 20:49 mono -> /Library/Frameworks/Mono.framework/Versions/Current/lib/mono
```

* If still you get an error message, then I would guess, as @spichardo mentioned, a mono issue. You can try the following:
  * `pip uninstall pythonnet`
  * delete the all `.egg` files in `site-packages`
  * reinstall mono from official source
  * add the link as described above
  * `pip install pythonnet` (uses 2.3.0)

Ideally, you can skip the first two by creating a new conda environment.

**Comment by riccardodelutio** [comment] 2017-05-15 13:39
Hello thanks for the answers!

@denfromufa  @spichardo 
I used `brew install mono` because I saw this was recommended but before that I had tried by following what's described in this http://www.mono-project.com/download/
and `pip install pythonnet` for pythonnet

@fractus 

`which python` outputs `/Users/riccardodelutio/anaconda2/bin/python` so it should be ok
`clr.so` does exist, could you just detail how I should 

> If clr.so exists, add the following link (point to your mono installation) and try again.

Thanks a lot

**Comment by fractus** [comment] 2017-05-15 17:29
This is a symbolic links, so use the `ln` command as follows:
```
vasilios@exumas: /usr/local/anaconda/lib
└─ $ ln -s /Library/Frameworks/Mono.framework/Versions/Current/lib/mono
```

**Comment by mcgradymvp** [comment] 2017-05-27 21:47
I was using `pip install pythonnet` and getting the error message as follows:

`Collecting pythonnet
  Using cached pythonnet-2.3.0.tar.gz
Building wheels for collected packages: pythonnet
  Running setup.py bdist_wheel for pythonnet ... error
  Complete output from command /Users/wangfan/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-build-lVXrQY/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/tmpBs9O8hpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 3.5.0.
  Updating NuGet.exe to 4.1.0.
  Update successful.
  MSBuild auto-detection: using msbuild version '14.0' from '/usr/local/Cellar/mono/5.0.0.100/lib/mono/xbuild/14.0/bin'.
  WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Restoring NuGet package NUnit.3.6.0.
  Restoring NuGet package NUnit.ConsoleRunner.3.6.0.
  Adding package 'UnmanagedExports.1.2.7' to folder '/private/var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-build-lVXrQY/pythonnet/packages'
  Adding package 'NUnit.3.6.0' to folder '/private/var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-build-lVXrQY/pythonnet/packages'
  Adding package 'NUnit.ConsoleRunner.3.6.0' to folder '/private/var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-build-lVXrQY/pythonnet/packages'
  Added package 'UnmanagedExports.1.2.7' to folder '/private/var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-build-lVXrQY/pythonnet/packages'
  Added package 'NUnit.ConsoleRunner.3.6.0' to folder '/private/var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-build-lVXrQY/pythonnet/packages'
  Added package 'NUnit.3.6.0' to folder '/private/var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-build-lVXrQY/pythonnet/packages'
  
  NuGet Config files used:
      /Users/wangfan/.config/NuGet/NuGet.Config
  
  Feeds used:
      /Users/wangfan/.nuget/packages/
      https://api.nuget.org/v3/index.json
  
  Installed:
      3 package(s) to packages.config projects
  
  >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
  
  XBuild Engine Version 14.0
  Mono, Version 5.0.0.0
  Copyright (C) 2005-2013 Various Mono authors
  
  >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
  
  XBuild Engine Version 14.0
  Mono, Version 5.0.0.0
  Copyright (C) 2005-2013 Various Mono authors
  		Configuration: ReleaseMono Platform: x64
  /private/var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-build-lVXrQY/pythonnet/src/runtime/Python.Runtime.csproj: error : Error executing task Copy: Error converting Property named 'SourceFiles' with value '$(TargetAssemblyPdb)' to type Microsoft.Build.Framework.ITaskItem[]: Can't concatenate Item list with other strings where an item list is expected ('@(_OutDirItem->'%(FullPath)')', 'Python.Runtime.pdb'). Use semi colon to separate items.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-build-lVXrQY/pythonnet/setup.py", line 405, in <module>
      zip_safe=False,
    File "/Users/wangfan/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/Users/wangfan/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/Users/wangfan/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Users/wangfan/anaconda2/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/Users/wangfan/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/Users/wangfan/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Users/wangfan/anaconda2/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/Users/wangfan/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/Users/wangfan/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Users/wangfan/anaconda2/lib/python2.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/Users/wangfan/anaconda2/lib/python2.7/distutils/command/build_ext.py", line 449, in build_extensions
      self.build_extension(ext)
    File "/private/var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-build-lVXrQY/pythonnet/setup.py", line 222, in build_extension
      subprocess.check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
    File "/Users/wangfan/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON27,PYTHON2,UCS2,MONO_OSX" /p:PythonBuildDir="/private/var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-build-lVXrQY/pythonnet/build/lib.macosx-10.7-x86_64-2.7" /p:PythonInteropFile="interop27.cs" /verbosity:minimal /t:Build' returned non-zero exit status 1
  
  ----------------------------------------
  Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... error
    Complete output from command /Users/wangfan/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-build-lVXrQY/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-ykHIOd-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    Checking for updates from https://www.nuget.org/api/v2/.
    Currently running NuGet.exe 4.1.0.
    NuGet.exe is up to date.
    MSBuild auto-detection: using msbuild version '14.0' from '/usr/local/Cellar/mono/5.0.0.100/lib/mono/xbuild/14.0/bin'.
    WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
    All packages listed in packages.config are already installed.
    
    >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
    
    XBuild Engine Version 14.0
    Mono, Version 5.0.0.0
    Copyright (C) 2005-2013 Various Mono authors
    
    >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
    
    XBuild Engine Version 14.0
    Mono, Version 5.0.0.0
    Copyright (C) 2005-2013 Various Mono authors
    		Configuration: ReleaseMono Platform: x64
    /private/var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-build-lVXrQY/pythonnet/src/runtime/Python.Runtime.csproj: error : Error executing task Copy: Error converting Property named 'SourceFiles' with value '$(TargetAssemblyPdb)' to type Microsoft.Build.Framework.ITaskItem[]: Can't concatenate Item list with other strings where an item list is expected ('@(_OutDirItem->'%(FullPath)')', 'Python.Runtime.pdb'). Use semi colon to separate items.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-build-lVXrQY/pythonnet/setup.py", line 405, in <module>
        zip_safe=False,
      File "/Users/wangfan/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/Users/wangfan/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/Users/wangfan/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/wangfan/anaconda2/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Users/wangfan/anaconda2/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/Users/wangfan/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Users/wangfan/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/wangfan/anaconda2/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/Users/wangfan/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Users/wangfan/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/wangfan/anaconda2/lib/python2.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/Users/wangfan/anaconda2/lib/python2.7/distutils/command/build_ext.py", line 449, in build_extensions
        self.build_extension(ext)
      File "/private/var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-build-lVXrQY/pythonnet/setup.py", line 222, in build_extension
        subprocess.check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
      File "/Users/wangfan/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON27,PYTHON2,UCS2,MONO_OSX" /p:PythonBuildDir="/private/var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-build-lVXrQY/pythonnet/build/lib.macosx-10.7-x86_64-2.7" /p:PythonInteropFile="interop27.cs" /verbosity:minimal /t:Build' returned non-zero exit status 1
    
    ----------------------------------------
Command "/Users/wangfan/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-build-lVXrQY/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-ykHIOd-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/08/_nrd2gy17lv97k9d6smtj41m0000gn/T/pip-build-lVXrQY/pythonnet/`

**Comment by mcgradymvp** [comment] 2017-05-27 21:50
I was using `pip install pythonnet` and getting the error message of `Failed building wheel for pythonnet`.
I recorded the error by _asciinema_:
[asciinema error message](https://asciinema.org/a/cg5xpzpwbrsaeg7nqg6n60h4b)

**Comment by denfromufa** [comment] 2017-05-27 22:29
@mcgradymvp can you try to install from master since you are using Mono 5.0, which just got fixed:

`pip install git+https://github.com/pythonnet/pythonnet`

**Comment by mcgradymvp** [comment] 2017-05-27 22:42
@denfromufa 
Thanks a lot. Now I can install pythonnet but got error when `import clr`

```
>>> import clr
The assembly mscorlib.dll was not found or could not be loaded.
It should have been installed in the `/Users/wangfan/anaconda2/lib/mono/4.5/mscorlib.dll' directory.
```

**Comment by denfromufa** [comment] 2017-05-27 22:48
@mcgradymvp please follow instructions from @fractus on how to symbolically link mscorlib.dll:

https://github.com/pythonnet/pythonnet/issues/392

**Comment by denfromufa** [comment] 2017-06-07 22:11
ok, so I managed to compile and use OSX + Mono 5.0 + pythonnet (master) on Mac Sierra.

Some additional instructions:

`brew install pkg-config`
`brew install glib --universal`

This should be on the same line:
`USE_OSX_FRAMEWORKS=0 ARCHFLAGS="-arch x86_64" pip install git+https:\\github.com\pythonnet\pythonnet`

**Comment by denfromufa** [comment] 2017-08-10 06:37
I'm putting together some notes for OSX here, please review @riccardodelutio @mcgradymvp @fractus:

https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX#osx-notes

**Comment by fractus** [comment] 2017-08-10 19:03
Looks good to me; two minor comments:
* Mono is installed in `/Library/Frameworks` with the official [installer](http://www.mono-project.com/download/). I would expect to brew to use `/usr/local/Cellar`, but I'm not using it.
* Formatting improvement; you could use triple ticks for the symbolic link to avoid confusion.

**Comment by lodb** [comment] 2017-08-25 14:42
When trying to follow these instructions (brew mono, add symbolic link, yada yada...), `USE_OSX_FRAMEWORKS=0 ARCHFLAGS="-arch x86_64" pip install git+https://github.com/pythonnet/pythonnet` executes without errors.

However, the problem is I'm running it in a virtualenv (using pyenv) with Python 3.4.3. When running `import clr`, I get the following error:
`Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import clr
ImportError: System.DllNotFoundException: python27
  at (wrapper managed-to-native) Python.Runtime.Runtime:Py_IsInitialized ()
  at Python.Runtime.Runtime.Initialize () [0x0000d] in <e96910e86ed845cb8f66189b0607b8cf>:0 
  at Python.Runtime.PythonEngine.Initialize () [0x00011] in <e96910e86ed845cb8f66189b0607b8cf>:0 
  at Python.Runtime.PythonEngine.InitExt () [0x00000] in <e96910e86ed845cb8f66189b0607b8cf>:0 `

It looks like installing from master via pip in a virtual environment still refers to python2.7 somewhere. Is it correct to assume pythonnet doesn't support python3 on OSX?

**Comment by denfromufa** [comment] 2017-08-25 21:00
@lodb no i think you missed something with your pythonnet installation in pyenv, which is not supported/tested by pythonnet. So I cannot tell you what is wrong with your installation due to this untested scenario with pyenv. I suggest to install on python 3.4 without using pyenv. I used pyenv once and was quite unhappy with it, but I may have missed some steps in using it.

**Comment by vkhombal** [comment] 2017-10-17 09:28
I had a version of Pythonnet+Mono setup that was working until a recent update of Mono. Now I get:

```
ImportError: dlopen(/Users/vh/anaconda/lib/python3.5/site-packages/clr.cpython-35m-darwin.so, 2): Library not loaded: /Library/Frameworks/Mono.framework/Versions/5.2.0/lib/libmonosgen-2.0.1.dylib
  Referenced from: /Users/vh/anaconda/lib/python3.5/site-packages/clr.cpython-35m-darwin.so
  Reason: image not found
```

My /Library/Frameworks/Mono.framework/Versions/ looks like this
```
MAC:lib vh$ ls /Library/Frameworks/Mono.framework/Versions/
5.4.0	Current
```

Can you please advice on what to update make it point to the correct Mono version?

**Comment by denfromufa** [comment] 2017-10-17 12:36
@vkhombal clearly pythonnet is trying to load mono version 5.2.0, but you have upgraded to 5.4.0. So you may need to update your symbolic links if that helps.

**Comment by vkhombal** [comment] 2017-10-17 14:08
@denfromufa 

hi updated the softlink, but it still is looking for the 5.2.0
```
MAC:lib vh$ pwd
/Users/vh/anaconda/lib
MAC:lib vh$ ls -l mono
lrwxr-xr-x  1 vh  staff  58 Oct 17 10:03 mono -> /Library/Frameworks/Mono.framework/Versions/5.4.0/lib/mono
```

```
ImportError: dlopen(/Users/vh/anaconda/lib/python3.5/site-packages/clr.cpython-35m-darwin.so, 2): Library not loaded: /Library/Frameworks/Mono.framework/Versions/5.2.0/lib/libmonosgen-2.0.1.dylib
  Referenced from: /Users/vh/anaconda/lib/python3.5/site-packages/clr.cpython-35m-darwin.so
  Reason: image not found
```

**Comment by denfromufa** [comment] 2017-10-17 14:28
@vkhombal let's continue discussion in gitter chat: https://gitter.im/pythonnet/pythonnet

**Comment by denfromufa** [comment] 2017-10-24 17:35
updated instructions from @vkhombal:

https://github.com/pythonnet/pythonnet/issues/555#issuecomment-339069190

**Comment by nsbruce** [comment] 2017-11-06 22:57
@denfromufa  a quick comment on the troubleshooting link at https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX#osx-notes

In the last bullet point, ```USE_OSX_FRAMEWORKS=0 ARCHFLAGS="-arch x86_64" pip install git+https:\github.com\pythonnet\pythonnet``` the slashes are backwards and one is missing. I think it should read as:

```USE_OSX_FRAMEWORKS=0 ARCHFLAGS="-arch x86_64" pip install git+https://github.com/pythonnet/pythonnet```

**Comment by denfromufa** [comment] 2017-11-07 01:40
@nsbruce good catch and feel free to edit this wiki.

**Comment by ztl8702** [comment] 2018-11-09 18:57
@denfromufa 

What is the reason for prefixing `pip install...` with `USE_OSX_FRAMEWORKS=0 ARCHFLAGS="-arch x86_64"`? 

If I build from source (`python3 setup.py bdist_wheel --xplat`), why do I _not_ have to set `USE_OSX_FRAMEWORKS=0 ARCHFLAGS="-arch x86_64"`?

**Comment by denfromufa** [comment] 2018-11-09 21:01
@ztl8702 my memory has been flushed in one year and I cannot find the original reason for this. Google search cannot help either. Try without and let us know the error!

**Comment by filmor** [comment] 2020-06-09 15:07
Since there have not been any updates in quite a while, I'll close this issue. Feel free to reopen and provide a information on the current state.

**Closed by filmor** 2020-06-09 15:07 UTC
Labels: documentation, waiting for user feedback
