### ISSUE TITLE
python.net  failing with .net 4.5

### ISSUE THREAD

**Issue by selvatheeban** [pythonnet/pythonnet#831] opened 2019-03-15 08:13 UTC
### Environment

-   Pythonnet version: 2.3.0 (64bit)
-   Python version:3.6 (64bit)
-   Operating System:Windows 10 pro

### Details

-   I am trying to use pythonnet in my .net console application ( .net frame work 4.5 )but its end up with issue [ System.BadImageFormatException]  Note: I have installed python 3.6 then i have installed pythonnet with 'pip install pythonnet'  then made a reference of Python.Runtime dll to my console application
 Even i have tried with using nuGet package while implies same issue . 

/# code #/
        {
            PythonEngine.Initialize();
            PythonEngine.BeginAllowThreads();
            using (Py.GIL())
            {
                dynamic np = Py.Import("numpy");
                Console.WriteLine(np.cos(np.pi * 2));
            }
        }

##Note: but this same code is working fine with Console application with ".net framework 4 "

**Comment by filmor** [comment] 2019-03-15 08:26
`System.BadImageFormatException` in this context means that your program is running with the wrong bitness. Configure it to be explicitly 64 bit and you should be fine. By default it will be 32 bit.

**Comment by selvatheeban** [comment] 2019-03-15 10:38
thanks a lot. Actually build preference 32 bit  has been enabled , Now i disabled it  and my console app is working fine.

Now am trying the same thing with  **web api** .net framework 4.5
-      [HttpGet]
        [Route("api/pythonnet")]
        public HttpResponseMessage TableIdentification()
        {
        using (Py.GIL())
                {
                dynamic np = Py.Import("numpy");
                Console.WriteLine(np.cos(np.pi * 2));
                return Request.CreateResponse(HttpStatusCode.OK, new ResponseMessage("CODE_001", "Success", np))
}
}

-      Here in default  prefer 32 bit is disabled thus its working on 64bit 
-      Even-though same error is happening while running the web api 

> System.BadImageFormatException : Could not load file or assembly 'Python.Runtime' or one of its dependencies. An attempt was made to load a program with an incorrect format

**Comment by filmor** [comment] 2019-03-15 10:42
This depends on your IIS settings, not only on the DLL. For executables, the configured bitness preference is important, as that is the entry point. I'm going to close this now as it's not a bug in Python.NET.

**Closed by filmor** 2019-03-15 10:42 UTC
