### ISSUE TITLE
NotSupportedException on PythonEngine.Shutdown()

### ISSUE THREAD

**Issue by simon-chester** [pythonnet/pythonnet#2149] opened 2023-05-03 09:46 UTC
### Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.9
-   Operating System: Debian GNU/Linux 11 (bullseye)
-   .NET Runtime: 7.0.5

### Details

-   Describe what you were trying to get done.

I'm invoking `PythonEngine.Shutdown()`, which throws an exception: 'NotSupportedException: 'BinaryFormatter serialization and deserialization are disabled within this application'.

I can work around this by adding the following to my project file:
  `<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>`

I'm nervous about this because Microsoft has decreed it to be 'unsafe'. Is there a better way?

**Comment by nlogozzo** [comment] 2023-05-03 16:44
Duplicate of #2107

**Closed** 2023-05-03 16:55 UTC
