### ISSUE TITLE
how cant i get the print in PythonEngine.Exec("print('123')"); i want to get the content  when i use PythonEngine.Exec to print

### ISSUE THREAD

**Issue by chendingqi** [pythonnet/pythonnet#1433] opened 2021-04-02 07:38 UTC
### Environment

-   Pythonnet version:3.8
-   Python version:3.8
-   Operating System:windows64
-   .NET Runtime:framework4.7

### Details

-   i want to get the print content when i use PythonEngine.Exec to implement python

    _TODO_

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.
![image](https://user-images.githubusercontent.com/37861405/113393536-64930b80-93c9-11eb-88c2-9a2baf6b9ef6.png)
![image](https://user-images.githubusercontent.com/37861405/113393546-68269280-93c9-11eb-8d89-a303cf8366a0.png)

how can i get 123?

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by lostmsu** [comment] 2021-04-02 07:40
Duplicate of https://github.com/pythonnet/pythonnet/issues/1432

**Closed** 2021-04-02 07:40 UTC
