### ISSUE TITLE
No completion for .NET objects in Jupyter

### ISSUE THREAD

**Issue by tom-bowles** [pythonnet/pythonnet#806] opened 2019-01-16 14:38 UTC
### Environment

-   Pythonnet version: 2.3.0 (https://anaconda.org/pythonnet/pythonnet)
-   Python version: 3.6.8 (Anaconda)
-   Operating System: Windows 10

### Details

In a notebook, evaluate:
```
    abcde =12
```
Then type "ab" and hit Tab. Completion list shows with "abcde".

Then evaluate:
```
    import clr
    clr.AddReference("System.Collections")
    from System.Collections import ArrayList
    abcde = ArrayList()
```
Type "ab" and hit Tab. No completion list shows.

Set the variable back to "12". Now completion works for it. Completion seems to show no variables containing .NET objects.

**Comment by denfromufa** [comment] 2019-01-16 23:51
@tom-bowles have you checked this in ipython console/qtconsole/jupyterlab? most likely this is an issue in jupyter, but also I cannot reproduce this issue with pythonnet master branch and notebook server 5.7.0, jupyter 4.4.0, ipython 7.0.1, Python 3.6.5

**Comment by tom-bowles** [comment] 2019-01-17 08:55
I get the same behaviour in ipython console. I'm using pythonnet 2.30, notebook server 5.7.4, jupyter 4.4.0, ipython 7.2.0 and python 3.6.8.

**Comment by tom-bowles** [comment] 2019-01-17 13:17
Same with jupyterlab 0.35.4.

**Comment by filmor** [comment] 2019-01-22 08:34
This does sound really strange, I haven't observed this before. I'll have a look.

**Comment by nanoant** [comment] 2019-02-22 12:12
@filmor Thank for reporting the issue upstream and referencing it here.
I simply patched `parse/utils.py` around line 108 wrapping `unicode` call with `try/except`:
~~~py
    # Cast to unicode
    try:
        return unicode(source, encoding, errors)
    except UnicodeDecodeError:
        return ''
~~~
This have restored .NET completion in Jupyter for me.

**Comment by nanoant** [comment] 2019-02-25 09:43
The issue was fixed there in Jedi https://github.com/davidhalter/jedi/issues/1277 so I think it can be closed as soon there is an official (Conda?) release of Jedi with the fix available. Thank you.

**Comment by filmor** [comment] 2019-02-25 16:19
Since this was never really a Python.NET issue in the first place (I think announcing `__file__` as a DLL is fine, extension modules do this as well), I will close the issue. Thank you for the report and follow up :)

**Closed by filmor** 2019-02-25 16:19 UTC
