### ISSUE TITLE
c# implementation gives a bunch of exceptions

### ISSUE THREAD

**Issue by herrsa1** [pythonnet/pythonnet#713] opened 2018-08-08 11:49 UTC
### Environment

-   Pythonnet version:2.3.0
-   Python version:3.6(Anaconda)
-   Operating System:Windows 10

### Details

Im just running an empty console application on c# to test pythonnet out. it works fine and all but it takes a while to load up because of all the exceptions its throwing within those few seconds. I even just have an empty code block.

```
static void Main(string[] args)
        {
            using (Py.GIL())
            {

            }
            Console.ReadLine();
        }
```
[This](https://imgur.com/a/mIaqDX1) is the exception thrown and it goes on  for around 3 seconds

```
Exception caught: 'System.IO.FileLoadException' in Python.Runtime.dll 
("Could not load file or assembly '__StaticArrayInitTypeSize\=44' or one of its dependencies. 
The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)")
```

**Comment by filmor** [comment] 2018-08-09 18:49
This sounds to me like a duplicate of #703, do you agree?

**Comment by herrsa1** [comment] 2018-08-09 22:14
yeah thats what I was looking at but the error and language looked different so I decided to make another one. I can close it and just follow that one if you feel it's the same.

**Comment by filmor** [comment] 2018-08-19 07:14
I'll close this then, let's follow up in #703.

**Closed by filmor** 2018-08-19 07:14 UTC
