### ISSUE TITLE
Compatibility issue between argparse and pythonnet packages

### ISSUE THREAD

**Issue by sg08013** [pythonnet/pythonnet#404] opened 2017-02-24 07:51 UTC
### Environment

-   Pythonnet version: 2.3.0.dev1 (built from master on 23/02/2017)
-   Python version: 2.7.13 64bit
-   Operating System: Windows 7 64bit

### Details

-   I tested the pythonnet version from yesterday, 23/02/2017, as we are interested in the bug fix for the method overload issue #377. I noticed that we are now running into compatibility issues with the package argparse.

The package argparse now only works correctly, if the parsing of the command line arguments is done BEFORE the import statement of pythonnet (import clr).

If I revert my pythonnet version to pythonnet==2.2.2, then the problem disappears.

The following minimal test code illustrates the problem:
```
file: test.py
import argparse
# import clr # can't put it here, args.arg1 will be None

parser = argparse.ArgumentParser()
parser.add_argument('--arg1', '-a', help='argument 1', dest='arg1')
args = parser.parse_args()

import clr   
print('Argument 1 = ')
print(args.arg1)
```
Then I start the script from command line as
> python test.py --arg1 "Hello World"
```
If I run the code with the "import clr" statement after the call to parser.parse_args() then I get the desired output: 
Argument 1 =
hello world

However, if I put the "import clr" at the beginning of the file, I get the output:
Argument 1 =
None

**Comment by denfromufa** [comment] 2017-02-24 07:54
can you try before this pull request?

https://github.com/pythonnet/pythonnet/pull/347

**Comment by denfromufa** [comment] 2017-02-24 07:59
@filmor can you have a look at this, since this is most likely your pull request.

@vmuriart looks like you imported clr before setargv tests, hence this case was not tested:

https://github.com/pythonnet/pythonnet/pull/301

**Comment by vmuriart** [comment] 2017-02-24 08:04
@sg08013 can you verify that `sys.argv` is returning as `None` in the 2nd case. 
@denfromufa yup. Though looking at the issue, it would have been better to test `sys.argv != None` and then when it's imported shouldn't matter.

**Comment by denfromufa** [comment] 2017-02-24 08:08
no, we need to check that sys.argv is not modified. Checking against None is not enough. Generally `is not None` is better syntax.

**Comment by filmor** [comment] 2017-02-24 08:20
It should suffice to pass the information to `Initialize` that we are currently running in "module-mode" and skip the setting of argv in that case. I'll prepare a PR.

**Comment by denfromufa** [comment] 2017-02-24 08:27
hey, guys, sorry if I sounded rude. i'm actually rude by design :)

**Comment by sg08013** [comment] 2017-02-24 08:33
I just tested the value of sys.argv with the following code:
```
import argparse
import sys
print(sys.argv)
import clr 
print(sys.argv)
```
>python test.py --arg1 "bla"
['test.py', '--arg1', 'bla']
['']

**Comment by vmuriart** [comment] 2017-02-24 08:36
I can't think of a good way to write the test for this without breaking how `pytest` is designed to work. The best i can come up w is to have the test execute an external script via `subprocess` and report the result from it.

**Comment by vmuriart** [comment] 2017-02-24 08:40
I would also like to point out that this is issue `404 - sys.args not found`.

**Comment by denfromufa** [comment] 2017-02-24 08:44
@vmuriart you can check if sys has args with hasattr. sys.args does not exist yet after Py_Initialize().


@sg08013 thanks for reporting the issue!

**Comment by vmuriart** [comment] 2017-02-24 15:34
Fixed the test on 012b488af1a5f73bd7086923cbb9a437a30a5886 to reflect the behavior being seen. Its marked as `xfail` for now until we fix it.

Here's the test running against v2.2.2 showing that it worked. 
https://travis-ci.org/vmuriart/pythonnet/jobs/204904097

Thanks @sg08013 for reporting and providing the example.

**Comment by sg08013** [comment] 2017-02-24 16:29
@vmuriart I can't say yet, whether our issue is entirely resolved. We were having problems using overloaded methods from a C# assembly (in python). There were no crashes or exceptions, just empty return values. This part now runs through (=is resolved), but there is still something that does not work as expected (but this might be unrelated). 
I will let you know when I understand it better.

**Comment by sg08013** [comment] 2017-02-24 16:31
And thanks to all of you for taking care of this issue so quickly! That's highly appreciated.

**Closed** 2017-02-24 18:37 UTC
