### ISSUE TITLE
Failure in function selection according to parameters

### ISSUE THREAD

**Issue by uenz** [pythonnet/pythonnet#226] opened 2016-06-08 11:05 UTC
Hi,
until pythonnet 2.1.0 it was possible to call functions with the same name and different parameters. This fails with pythonnet 2.1.0
I have prepared minimal test functions like this, which return the input para string as string, int or float:
`public String Function(String para, ref String myout)`
`public String Function(String para,ref int myout)`
`public String Function(String para,ref float myout)`

and call them like this
`from Test import TestClass`
`dummy=TestClass()`

`print dummy.Function('Echo',str())`
`print dummy.Function('42',int())`
`print dummy.Function('3.144',float())`

With pythonnet==2.0.0 the result is as expected
`(u'Echo', u'Echo')`
`(u'42', 42.0)`
`(u'3.144', 3.144)`

pythonnet==2.1.0 returns a TypeError: No method matches given arguments

I have a sample dll and py as a zip, but unfortunately the upload fails.
(Unfortunately, we don’t support that file type. )

**Comment by denfromufa** [comment] 2016-06-08 16:19
Method overloading was improved since pythonnet 2.0 - it could give you
wrong overloaded method before!

However ByRef is really complicated, since python does not support such a
concept directly.

In your case try this work-around by passing the actual CLR type:

import System
dummy.Function('Echo',System.String(""))

Here is WIP patch that handles ByRef argument types. Just need to do more
testing:

https://github.com/pythonnet/pythonnet/pull/227

**Comment by uenz** [comment] 2016-06-09 05:25
Thanks for the response.
The workaround with 
dummy.Function('Echo',System.String("")) 
unfortunately gives the same type error as mentioned.

**Comment by denfromufa** [comment] 2016-06-09 05:54
Are you calling static or instance methods? If instance method, then did
you initialize the object?

Can you share your full example (both C# and python) in a gist on github?

**Comment by denfromufa** [comment] 2016-06-09 05:58
Anyway you can grab the branch from my pull request and build it yourself.

**Comment by uenz** [comment] 2016-06-10 05:07
The code of the branch works well!

A gist with the code is here:
https://gist.github.com/uenz/b5eec565e4484595af98e0a620194229
The DLL code is stripped down only to show the issue.
Unfortunaltey i found no way to add also the compiled C# dll.

**Comment by denfromufa** [comment] 2016-09-14 03:10
This issue requires implemented clr.Reference type properly in pythonnet. The issue is that during overload it is not possible to distinguish 2 overloads with the same signature except byref switched to byval. This is perfectly valid code in C#.

Also related issues here:

https://github.com/pythonnet/pythonnet/issues/228

https://github.com/pythonnet/pythonnet/issues/236

**Comment by heri16** [comment] 2017-05-06 01:26
Is there a fix or workaround for this yet?

**Comment by denfromufa** [comment] 2017-05-06 04:33
no fix yet, the workaround is using Reflection.

**Comment by filmor** [comment] 2022-06-14 13:29
This should be fixed nowadays, if not, we should treat that as a new issue.

**Closed by filmor** 2022-06-14 13:29 UTC
Labels: enhancement
