### ISSUE TITLE
pythonnet should support calling methods on C# objects derived from DynamicObject and members exposed via TryGetMember / TryInvoke 

### ISSUE THREAD

**Issue by kasajian** [pythonnet/pythonnet#1217] opened 2020-09-06 23:11 UTC
### Environment

-   Pythonnet version: latest
-   Python version: latest
-   Operating System: Windows 10

### Details

    If a C# class exposes properties and methods dynamically, such as when the information isn't available at compile time, it derives from DynamicObject and overrides TryGetMember and TryInvoke (or TryInvokeMember).
    These types of methods and properties aren't accessible from Python.NET

    Right now, it says the attribute is missing.  Instead, Python.NET should see if the CLR object is derived from DynamicObject , and if so, call TryGetMember  on it, then call TryInvoke on that.   I'm not sure methods exposed via TryInvokeMember will work, but I'm not sure.    But Python.NET can at least implement calling properties and methods exposed via TryGetMember  / TryInvoke.

Take a look at the example sample class "DynamicNumber" in MSDN:
https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.dynamicobject.tryinvoke?view=netcore-3.1

That class exposed publicly via a C# assembly should be usable from Python.NET

Also "DynamicDictionary" is another example at https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.dynamicobject.tryinvokemember?view=netcore-3.1

The rest of the Try members can also be implemented, incrementally, to add more and more functionality.   But supporting TryGetMember and TryInvoke would be minimum required.

**Comment by filmor** [comment] 2020-09-07 10:29
This is a duplicate of https://github.com/pythonnet/pythonnet/issues/72. There is also a workaround for types deriving from `DynamicObject` (which should be most dynamic types) in that thread.

**Closed by filmor** 2020-09-07 10:29 UTC
