### ISSUE TITLE
Initializing iList with class results in "TypeError: type(s) expected"

### ISSUE THREAD

**Issue by somelinguist** [pythonnet/pythonnet#257] opened 2016-09-01 16:24 UTC
In IronPython, I can initialize a .NET iList of a class I defined like this:

``` python
import clr
clr.AddReference("System.Collections")
from System.Collections.Generic import List

class MyClass(object):
    def __init__(self, e = ""):
        self.title = e

li=List[MyClass]()
list(li)
li.Add(MyClass("title"))
print list(li)
```

This works in IronPython, printing `[<MyClass object at 0x000000000000006C>]`.

With PythonNet, however, I get `TypeError: type(s) expected` at the line with `li=List[MyClass]()`.
Making a list of generic types (int, str, etc) instead of a class does work fine.

Should I expect this from PythonNet? Is there another way to do what I want to accomplish if the above is not possible in PythonNet?

**Comment by denfromufa** [comment] 2016-09-02 13:41
This issue looks like a duplicate of this one and I'm not aware of any workaround yet:

https://github.com/pythonnet/pythonnet/issues/94

This could be implemented like suggested in that issue by @tonyroberts

**Comment by somelinguist** [comment] 2016-09-02 23:03
Yes, it looks like the same issue as far as I can tell.

**Closed** 2020-06-09 15:15 UTC
Labels: duplicate

**Comment by justinxuereb** [comment] 2022-08-04 07:50
I am having the same error as @somelinguist and also went through @denfromufa #94 but I could not understand the solution to it. Can someone tell me how to solve the error please?
