### ISSUE TITLE
Use .NET XML doc for `__doc__`

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#1867] opened 2022-07-11 17:08 UTC
See https://docs.microsoft.com/en-us/archive/msdn-magazine/2019/october/csharp-accessing-xml-documentation-via-reflection

**Comment by filmor** [comment] 2022-07-11 17:26
I believe this is a duplicate of https://github.com/pythonnet/pythonnet/issues/374

**Closed** 2022-07-11 17:30 UTC
Labels: enhancement
