### ISSUE TITLE
making a delegate with more than 10 arguments crashes

### ISSUE THREAD

**Issue by gijzelaerr** [pythonnet/pythonnet#537] opened 2017-09-04 12:50 UTC
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6 32 bit
-   Operating System: Windows 10

### Details

```
import clr
import System
System.Action[str, str, str, str, str, str, str, str, str, str](print)
Out[4]: <System.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] at 0x7ba75b0>
System.Action[str, str, str, str, str, str, str, str, str, str, str](print)
Unhandled Exception: System.ArgumentException: Type name was too long. The fully qualified type name must be less than 1,024 characters.
Parameter name: fullname
   at System.Reflection.Emit.TypeBuilder.Init(String fullname, TypeAttributes attr, Type parent, Type[] interfaces, ModuleBuilder module, PackingSize iPackingSize, Int32 iTypeSize, TypeBuilder enclosingType)
   at System.Reflection.Emit.ModuleBuilder.DefineType(String name, TypeAttributes attr, Type parent)
   at Python.Runtime.DelegateManager.GetDispatcher(Type dtype)
   at Python.Runtime.DelegateManager.GetDelegate(Type dtype, IntPtr callable)
   at Python.Runtime.DelegateObject.tp_new(IntPtr tp, IntPtr args, IntPtr kw)
   at e__NativeCall.Call_3(IntPtr , IntPtr , IntPtr , IntPtr )
   at Python.Runtime.MetaType.tp_call(IntPtr tp, IntPtr args, IntPtr kw)

Process finished with exit code -532462766

```

**Comment by denfromufa** [comment] 2017-09-04 13:48
what about other python versions? have you tried from the master branch?

**Comment by denfromufa** [comment] 2017-09-04 13:56
ok, python 2.7 and master branch both fail with the same error.

**Comment by filmor** [comment] 2020-06-09 15:32
I can confirm that this is still an issue.

**Comment by filmor** [comment] 2021-08-06 09:02
Seems to be fixed now.

**Closed by filmor** 2021-08-06 09:02 UTC
Labels: bug
