### ISSUE TITLE
[py 3.5] Instantiating subclass throws exception: TypeError: no constructor matches given arguments

### ISSUE THREAD

**Issue by Thraka** [pythonnet/pythonnet#252] opened 2016-08-31 00:35 UTC
_I'm new to this_

I'm using Python 3.5

I have my own .NET library class that does **not** have a parameterless constructor. I want to subclass it in python and create a parameterless constructor. However, python always throws an error when I do not specify parameters on creating an instance of the class. The parameters for the C# class constructor is `int, int`.

**sub class**

```
class TestConsole(SadConsole.Consoles.Console):

    def __init__(self):
        super().__init__(80, 25)
        super().Print(0, 0, "right constructor")

    def __init__(self, x, y):
        super().__init__(x, y)
        super().Print(0, 0, "wrong constructor")
```

**calling code that crashes with error**

```
new_console = TestConsole()
```

**force parameters, it works fine, but obviously prints out "wrong constructor"**

```
new_console = TestConsole(80, 25)
```

**Comment by denfromufa** [comment] 2016-08-31 01:55
Can you share minimum reproducible `SadConsole.Consoles.Console`?

There is an open pull request about overloading on constructor and also
subclassing a python class that inherits from .NET class is buggy (see
mailing list).

**Comment by Thraka** [comment] 2016-08-31 03:25
[class-test.zip](https://github.com/pythonnet/pythonnet/files/446361/class-test.zip)

**Comment by denfromufa** [comment] 2016-08-31 14:48
This is error in both pythonnet and ironpython:

![image](https://cloud.githubusercontent.com/assets/7870949/18133365/f0134064-6f5f-11e6-8981-c4400f0909eb.png)

![image](https://cloud.githubusercontent.com/assets/7870949/18133401/0fc22ba0-6f60-11e6-9201-11b41764bea2.png)

**Comment by Thraka** [comment] 2016-08-31 19:05
Is this a scenario we can cover some how? It seems that a .NET type as a base class, the .NET base class gets initialized before the Python inherited class, which is opposite to how it seems it should work.

**Comment by denfromufa** [comment] 2016-08-31 21:37
Looking at history this limitation was originally like that in pythonnet.

And some updates on subclassing more recently here from @tonyroberts with
so many limitations listed:

http://code.activestate.com/lists/pythondotnet/1397/

So have you looked at using python closures? You would have your
alternative constructor logic in the outer function scope and use all .NET
methods in the inner scope.

**Comment by denfromufa** [comment] 2016-09-20 06:07
@Thraka you could just pass 2 dynamic objects (dyn_method and dyn_args) to constructor in C# not used on .NET side if null. Then just pass these dynamic object arguments to constructor on Python side to pass the python method and python arguments.

**Comment by denfromufa** [comment] 2016-09-20 06:11
```
namespace PythonTest
{
    public class Person
    {
        public string Name;
        public Person (string newName, dynamic dyn_method, dynamic dyn_args)
        {
            Name = newName;
            if (dyn_method != null)
            {
                dyn_method(dyn_args);
            }
        }
    }
}
```

**Comment by filmor** [comment] 2020-06-09 15:23
Since there have not been any updates in quite a while, I'll close this issue. Feel free to reopen and provide a information on the current state.

**Closed by filmor** 2020-06-09 15:23 UTC
Labels: enhancement

**Comment by angel88c** [comment] 2022-05-09 22:15
What's happen when the .Net constructor class returns a out string inside the parameters? 

` public TestClass(string name, out string error)
        {
            error = "Error in the Initialization";
            _name = name;

        }`
How can I get the out string parameter from python in the instance of object? I've tried using tuples and have error TypeError: iteration over non-sequence

`error =''
obj, error = TestClass("Angel", '')
print(obj)`

Thanks
