### ISSUE TITLE
Errors with example calling Python from .NET

### ISSUE THREAD

**Issue by shotskii** [pythonnet/pythonnet#249] opened 2016-08-22 23:12 UTC
When trying to run the numpy example from the Readme file I see the following error:
TypeError : long() argument must be a string or a number, not '0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'

This seems to be cause by the Py.kw function call. However, the numpy.array does not seem to be working properly.  The console output looks like this:

![image](https://cloud.githubusercontent.com/assets/21184490/17874842/775b6488-688b-11e6-8190-fb5f22c5211b.png)

This is from using the latest master branch and Python 2.7.  Has the array handling changed recently?

**Comment by denfromufa** [comment] 2016-08-23 16:51
@shotskii I found the version that was working. It actually took me few hours! This used to work in 2013:

https://github.com/fkarb/pythonnet_old/commit/1cfd7e2a417ea35f1251118da2ba9c996b45dffc

It looks like this was originally implemented by @patstew and then merged by @tonyroberts.

If you are willing to write tests (preferrably without numpy dependency, just using built-in array.array), or find exactly which version broke this (somewhere around 2013-2014), then please let me know, so that we can assist you, since I consider this feature pretty important.

![image](https://cloud.githubusercontent.com/assets/7870949/17901141/c0338ebe-6927-11e6-896f-d0f5c474b7e5.png)

**Comment by patstew** [comment] 2016-08-23 17:02
There is a marginally less ancient branch that worked (as far as I remember) here: https://github.com/patstew/pythonnet
I'm not sure when it broke, I don't use .net anymore.

**Comment by denfromufa** [comment] 2016-08-23 17:10
@patstew can also explain why arithmetic is implemented like this?
```
Mathematical operations involving python and literal/managed types must have the python object first, eg np.pi2 works, 2np.pi doesn't
```

**Comment by patstew** [comment] 2016-08-23 17:17
It's been a while, but as far as I remember it's a limitation of Microsoft's DynamicObject API. They only override the operations for TryBinaryOperation where the DynamicObject is first. I believe you could fix it by using the lower-level DynamicMetaObject, but using that API requires a load more code. I think.
The relevant stuff that I wrote is here: https://github.com/patstew/pythonnet/commit/0bd8c47f9b7559015c0a366db31ae4185c802aa2

**Comment by denfromufa** [comment] 2016-08-23 17:24
Oh, I see that this is DLR limitation, and confirmed by MS team. The
suggestion in this thread is to implement dynamic operators (-, +, *, etc.)
for arbitrary order to work:

http://stackoverflow.com/questions/2075649/dynamicobject-implicit-casting

**Comment by shotskii** [comment] 2016-08-24 13:52
@denfromufa it looks like you may be looking in to this already.  I can try to narrow down where this broke.  I agree it is an important feature.  I can't commit to when I will be able to start looking at this however.  Hopefully soon.

**Comment by Thraka** [comment] 2016-08-31 04:05
Does this prevent normal `implicit operator` declarations from working? Using two pure .NET objects through python I'm getting a cast error. The equivalent code in .NET would work fine (when it goes through the implicit operator)

**Comment by denfromufa** [comment] 2016-08-31 14:57
I believe implicit operator does not work and please open a separate issue
for this, since it is not related to this issue. In IronPython a special
conversion function is provided due to this limitation:

http://www.voidspace.org.uk/ironpython/dark-corners.shtml#implicit-conversion

**Comment by vmuriart** [comment] 2017-02-17 04:37
@denfromufa I found out today that `numpy` is pre-installed in Travis build workers. We could use those if we ever get the embedded tests running.

**Comment by vmuriart** [comment] 2017-03-07 06:23
Looks like this broke during the Develop/Py3 branch merges. 26cc77ba71b43722a705788db1cb9f16ac0d24cb

**Comment by vmuriart** [comment] 2017-03-08 05:50
I got this issue fixed, I'll merge in the fix after `v2.3.0` release

**Comment by denfromufa** [comment] 2017-03-08 14:51
@vmuriart this is great! @JimSEOW was looking for this fix:

https://github.com/Lodomir/PythonInterface/issues/2#issuecomment-275654916

**Comment by vmuriart** [comment] 2017-03-08 15:17
It requires some changes to the converter thats why I'm holding it off till next release since we already have a couple changes to converter/method override on this release.

**Comment by vmuriart** [comment] 2017-03-12 19:01
#427 will fix this in case anyone wants to review

**Closed** 2017-03-14 04:28 UTC
Labels: bug, regression
