### ISSUE TITLE
Release opened dll

### ISSUE THREAD

**Issue by picibucor** [pythonnet/pythonnet#513] opened 2017-07-18 13:34 UTC
### Environment

-   Pythonnet version:  2.3
-   Python version:  3.4
-   Operating System:  win7 / win10

### Details
I would like to release loaded .dll files.
Like the     clr.ClearProfilerData()    which releases all the dll-s in an IronPython environment.

**Comment by denfromufa** [comment] 2017-07-18 20:01
@picibucor multiple workarounds available: load into separate appdomain or load assembly using reflection.

**Comment by stevehv** [comment] 2017-09-26 19:58
@denfromufa New to pythonnet, could you give some pointers on where to find more info about any of the workarounds? I found some examples where `clr.System.Reflection.Assembly.LoadFile(".../file.dll")` is used followed by `clr.file`, but this does not seem to work (clr does not contain `file`). I am trying to reload an updated version of an assembly on the fly without restarting python runtime.

**Comment by denfromufa** [comment] 2017-09-26 20:37
@stevehv you mean `file` from this SO answer?

https://stackoverflow.com/a/6365969/2230844

If yes, then it is namespace of that loaded assembly. I edited that answer in hope that it is more clear now.

**Comment by stevehv** [comment] 2017-09-26 21:30
@denfromufa Thanks! I meant that answer indeed.
In the updated answer you call `dll1 = Assembly.LoadFile("C:\Python\Python27-32\Lib\site-packages\Python.Runtime.dll")`. I'm not sure what, if anything, this line does, becauses `clr.Python.Runtime` and `clr.Python.Runtime.PythonEngine` already exist even if I run the updated answer with that line removed.

AddReference works as expected:
```python
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import clr
>>> sys.path.append("C:/")
>>> dll1 = clr.AddReference("MyTest")
>>> import MyTest
>>> MyTest
<module 'MyTest'>
```

Reflection does not work like in example:
```python
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr
>>> from System.Reflection import Assembly
>>> dll1 = Assembly.LoadFile("C:/MyTest.dll")
>>> clr.MyTest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'clr' has no attribute 'MyTest'
```
MyTest is a simple class library with namespace MyTest containing class MyClass.

**Comment by stevehv** [comment] 2017-10-17 20:28
@denfromufa Sorry to bug you, but any information on how to release a dll with any of the workarounds you mentioned would be greatly appreciated.

**Comment by denfromufa** [comment] 2017-10-18 14:08
@stevehv can you share minimal C# & Python projects that reproduces this problem in VS solution?

**Comment by stevehv** [comment] 2017-10-18 19:09
@denfromufa Minimal example: https://github.com/stevehv/pythonnet_release_opened_dll

**Comment by fbalobanov** [comment] 2019-06-11 01:51
A solution that worked for me:

1. load dll using reflection using byte[] instead of file path
2. use Activator to create an instance of an required object

`import os
import sys
import clr
from System.Reflection import Assembly
from System.IO import File
from System import Activator

path = 'D:\\dll_name1.dll'

dll = Assembly.Load(File.ReadAllBytes(path))

obj_type = dll.GetType("MyNamespace.ObjectType")

#instance of the object
obj = Activator.CreateInstance(obj_type)

# or
def ObjectType(): return Activator.CreateInstance(obj_type )
obj = ObjectType()

 `
Links that I used:
https://stackoverflow.com/questions/1137781/correct-way-to-load-assembly-find-class-and-call-run-method
https://blogs.msdn.microsoft.com/raulperez/2010/03/04/net-reflection-and-unloading-assemblies/
https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-load-assemblies-into-an-application-domain

if loaded dll contains links to other user dlls it could fail to find them, so here are a couple of solutions:
https://stackoverflow.com/questions/15883109/createinstanceandunwrap-fails-to-load-assembly

I just referenced another dll that I needed in the first dll:
'#additional dll needed for dll1 work
path2 = 'D:\\dll_name2.dll' 
Assembly.Load(File.ReadAllBytes(path2))'

Ultimately this method made possible to recompile dll in C# and reload it in Python without restarting an interpreter or kernel at all, which is a way more convenient than reloading it all the time

Solution with Appdomain should be something like this:

`
from System import AppDomain
domain = AppDomain.CreateDomain("NewDomainName")
runnable = domain.CreateInstanceFromAndUnwrap(path, "MyNamespace.ObjectType")
object = runnable.Run()
`

**Comment by filmor** [comment] 2020-06-09 16:00
This issue is not specific to Python.NET, so I'll close this issue.

**Closed by filmor** 2020-06-09 16:00 UTC
Labels: enhancement

**Comment by numericsguy** [comment] 2020-11-10 17:44
@filmor The feature requested in this issue is really important for doing development in systems that use Python as their extension language. Currently, I have to ask all users to log out of the host system whenever I want to exchange a dll. The feature requested in this issue would allow me to leave the system in a clean state. I can also live with something like `clr.RemoveReference("MyAssembly") `. Or that the resources are released automatically as soon as they are not in scope anymore. Just something that allows me to leave the system in a clean and controlled state. Why do you block resources without any need to do so?

**Comment by filmor** [comment] 2020-11-11 06:39
I'm fully aware that this is a useful feature, but .NET Framework does not allow you to unload a DLL while it's still referenced in any AppDomain. This is a problem with .NET, not with Python.NET. The functionality you are requesting is not possible without explicit use of AppDomains. There are multiple examples in this issue on how to do that.

In .NET Core we might be able to build something using `AssemblyLoadContext`, but this is very specific functionality and I would rather like us to stick to .NET Standard functionality.

**Comment by numericsguy** [comment] 2020-11-11 08:54
@filmor Thank you very much for your detailed explanation. I understand now.
