### ISSUE TITLE
Domain reload crashes when .NET object points to PythonException

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#1371] opened 2021-01-28 17:40 UTC
Please see this comment: https://github.com/pythonnet/pythonnet/pull/1361#discussion_r564786550

We disabled `test_method_parameters_change`. Domain reload needs to be fixed so that holding a reference to `PythonException` is permitted.

I also suspect holding a reference to `PyObject` in this situation would break refcount based on the source code (serialization does not IncRef => original and deserialized object will both call DecRef).

**Comment by lostmsu** [comment] 2021-01-28 17:41
@benoithudson @BadSingleton can one of you pick this up?

**Comment by BadSingleton** [comment] 2021-01-29 15:36
Yup, I'll give it a go

**Comment by BadSingleton** [comment] 2021-01-29 16:28
The issue is actually that the `PythonException` class is not explicitly marked as `[Serializable]` (also needs the deserializaiton ctor)

**Comment by BadSingleton** [comment] 2021-02-02 14:49
There is also something going on with the refcount. Not sure yet how, but the AggregateException (and InnerExceptions) lives for longer than it should.

**Comment by filmor** [comment] 2021-02-02 16:32
I ran into something like this on #1373, see https://github.com/pythonnet/pythonnet/pull/1373/commits/53e51a28df8604bd016ee83f81f41d32a5f84de3. `_pyvalue` doesn't seem to be tracked properly.

**Comment by filmor** [comment] 2022-06-14 13:59
The test is enabled nowadays, I guess this one is solved.

**Closed by filmor** 2022-06-14 13:59 UTC
