### ISSUE TITLE
Crash when file or folder from import gets modified (Memory Corrupt...)

### ISSUE THREAD

**Issue by ArtruneTranspara** [pythonnet/pythonnet#1357] opened 2021-01-19 00:43 UTC
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.8
-   Operating System: Win10, WinServer (2019,2016)
-   .NET Runtime: 4.7

### Details

-   Describe what you were trying to get done.
    I have a webservice that invokes a python.py file and gets its result, it works fine, the webservice is 
    hosted in IIS, however whenever I change something from the file or folder where the python file I 
    imported is it corrupts the memory and I have to restart the app pool or restart iis, To import the file I 
    just use: 
    `Py.Import(INTERFACE_FILE_NAME);`
    Is there some fundamental thing I'm missing?

    This is the error message I get, it seems to be crashing when the .py file has been 
     modified and it tries import it again. :
    

>System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Python.Runtime.Runtime.PyImport_ImportModule(String name)
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize() 

What I've tried:

What hasn't worked:
Py.Import
PyModule.FromString (Access Violations...)

What has worked:
Using any of the import methods but stopping the app pool, editing file and restarting the app pool (I don't like this option)

**Comment by ArtruneTranspara** [comment] 2021-01-19 00:48
Sometimes it fails on the constructor, trying to intialize the python engine again, and sometimes it just fails without even calling any function, seems that the webservice memory gets corrupt.

**Comment by filmor** [comment] 2021-01-19 08:11
Could you test whether this occurs on the current master as well?

**Comment by ArtruneTranspara** [comment] 2021-01-20 16:45
> Could you test whether this occurs on the current master as well?

Absolutely. Are there any specific steps to compile the project? Or just cloning and compiling? 
I tried looking on the wiki/tutorial section but didn't find much.

**Comment by filmor** [comment] 2021-01-20 21:45
If you just want to use it from a .NET project, run

    python setup.py configure

once to set it up. You need a .NET Core SDK installed.

See https://github.com/pythonnet/pythonnet/wiki/Development-Guidelines#building-installing-and-testing-locally

**Comment by ArtruneTranspara** [comment] 2021-01-20 22:59
At first glance it does seem to fix the issue, I'm still to run some more tests but I think this was it.
Just out of curiosity, do you know what change? Could you link me to the commit that fixes this issue?
Thanks, will run other tests later today.

**Comment by filmor** [comment] 2021-01-21 06:47
Not really, there's been a lot of significant changes since 2.5.1, and in particular there were quite a few that fixed "soundness". I guess you'd need to bisect to find the specific commit.

**Comment by ArtruneTranspara** [comment] 2021-02-04 14:56
Seems the updates that are now on master fixed the memory corruption, I was unable to track which commit fixed it but I'll close the issue.
thanks @filmor

**Comment by ArtruneTranspara** [comment] 2021-04-01 01:09
Seems it was pure coincidence. I still get the same errors after modifying the .py file I import.

Is there a safe way to unimport-reimport a file if I know there will be changes?

I tried PythonEngine.Shutdown -> modify imported file -> PythonEngine.Initialize
And then call a function but that didn't work and ends up corrupting the memory aswell, Is my only choice to restart the process when I make changes to imported scripts? (Because I know that works, but would be an undesirable workaround)

**Comment by lostmsu** [comment] 2021-04-01 05:04
@ArtruneTranspara some Python libraries are notoriously unable to work correctly with engine shutting down and starting again in the same process. I think `numpy` is one of them.

I am not saying Python.NET is not at fault, but until we see more details, it is impossible to investigate. At the first glance I do not even understand why do you have to shut down the Python engine. Does `Py.Import` crash with access violation when you try running it after the file changes? You may want to try use `PythonEngine.Compile` (or `PyModule.FromString` in the recent builds) instead of `Import`, and try passing new imaginary `filename` every time.

**Comment by ArtruneTranspara** [comment] 2021-04-01 05:25
> @ArtruneTranspara some Python libraries are notoriously unable to work correctly with engine shutting down and starting again in the same process. I think `numpy` is one of them.
> 
> I am not saying Python.NET is not at fault, but until we see more details, it is impossible to investigate. At the first glance I do not even understand why you have to shut down the Python engine. Does `Py.Import` crash with access violation when you try running it after the file changes? You may want to try using `PythonEngine.Compile` (or `PyModule.FromString` in the recent builds) instead of `Import`, and try passing new imaginary `filename` every time.

Yes I did come across the numpy threads (but I’m not using numpy just requests and json mostly inside the python file I import).
I wouldn’t want to shutdown the python engine, I was doing tests.
Yes I get access violations when I try running after the file changes.
I will try PyModule from.string tomorrow and see how that works out.

**Comment by lostmsu** [comment] 2021-04-01 05:28
@ArtruneTranspara wait, "hosted in IIS"? This might also indicate, that multiple app domains are involved. In this case the problem might come from Python.NET if it is initialized in 2 of them simultaneously.

**Comment by ArtruneTranspara** [comment] 2021-04-01 15:38
Hello it is hosted in IIS. From what I've read it is of my understanding that IIS will create more AppDomains if on different IIS Websites (Atleast on my current use case that would be acceptable as my page and webservices live all under the same IIS Website, I could be wrong on the IIS behavior though)

Trying PyModule.FromString and posting updates..

**Comment by ArtruneTranspara** [comment] 2021-04-01 18:57
@lostmsu  I tried using PyModule.FromString. I'm getting a funny behavior. Subsequent calls to PyModule.FromString throw an AccessViolationException if the underlying code wasn't modified, if i for example, modify the output of a function and then call PyModule.FromString again then it works no problem, If I add another function at the bottom of the file but don't change existing functions and try PyModule.FromString then I get AccessViolations too..

**Comment by lostmsu** [comment] 2021-04-02 08:04
@ArtruneTranspara can you produce a minimal example of code, that causes the error? Does it reproduce outside of IIS?

**Comment by ArtruneTranspara** [comment] 2021-04-02 18:42
Seems that on a winform app I'm able to re import the module without problems, this is the code i used for both:
`        private void LoadInterfaceModule()
        {
            string guidString = Guid.NewGuid().ToString();
            string code = File.ReadAllText(Path.Combine(AssemblyDirectory, "interface.py"));
            interfaceModule = PyModule.FromString(guidString, code);
        }`
I was debbugging on the IIS one and it seems that app domains are the same. Not sure what might be going on there.

**Comment by lostmsu** [comment] 2021-04-02 19:58
Are you acquiring GIL properly when you are doing the import second time? A web service running in IIS would get its handlers invoked by different thread each time.

**Comment by ArtruneTranspara** [comment] 2021-04-02 21:15
@lostmsu Actually I did on the winform one but on the IIS Webservice I forgot on re-invokes to the function. 
It seems to work on IIS aswell when using PyModule.FromString

**Comment by lostmsu** [comment] 2021-04-02 22:06
@ArtruneTranspara I'll close the issue. Please reopen, if it persists after adding a GIL lock.

**Closed by lostmsu** 2021-04-02 22:06 UTC

**Comment by ArtruneTranspara** [comment] 2021-04-03 01:01
@lostmsu  Right, thanks. It seems settled for now but I'll keep an eye open.

And for anyone wondering or using IIS, any modification to the files inside the bin folder will result in Recycled App Pools.
More [here](https://stackoverflow.com/questions/9802812/does-any-change-in-any-file-inside-bin-folder-cause-application-recycle-in-asp-n)
