### ISSUE TITLE
When run receive Unable to load DLL 'python27': The specified module could not be found. . (Exception from HRESULT: 0x8007007E)'

### ISSUE THREAD

**Issue by milindk** [pythonnet/pythonnet#566] opened 2017-10-30 12:45 UTC
### Environment

-   Pythonnet version:Latest
-   Python version:Python36
-   Operating System:Windows 10

### Details

-  Was trying to experiment with python for dot net so as to interact from dot net code with python libraries

    _TODO_

Just got the code from github. Executed the code adding debugger at Main function.
 at Python.Runtime.Runtime.Py_IsInitialized()
   
   at Python.Runtime.Runtime.Initialize() in C:\Users\Milind Kayangude\Desktop\Office_Documents\Python_Research\pythonnet-master\pythonnet-master\src\runtime\runtime.cs:line 214
   
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv) in C:\Users\Milind Kayangude\Desktop\Office_Documents\Python_Research\pythonnet-master\pythonnet-master\src\runtime\pythonengine.cs:line 167
   
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv) in C:\Users\Milind Kayangude\Desktop\Office_Documents\Python_Research\pythonnet-master\pythonnet-master\src\runtime\pythonengine.cs:line 145
   
   at Python.Runtime.PythonEngine.Initialize() in C:\Users\Milind Kayangude\Desktop\Office_Documents\Python_Research\pythonnet-master\pythonnet-master\src\runtime\pythonengine.cs:line 140
   
   at Python.Runtime.PythonConsole.Main(String[] args) in C:\Users\Milind Kayangude\Desktop\Office_Documents\Python_Research\pythonnet-master\pythonnet-master\src\console\pythonconsole.cs:line 35

**Comment by denfromufa** [comment] 2017-10-30 18:04
@milindk you installed pythonnet for python 2.7, but you need pythonnet built for python 3.6:

https://github.com/pythonnet/pythonnet/wiki/Installation
https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX

**Comment by denfromufa** [comment] 2017-11-02 13:55
Closing, since no feddback is received after posting instructions. Please report back if you get any other issue!

**Closed by denfromufa** 2017-11-02 13:55 UTC

**Comment by jengelman** [comment] 2017-11-30 20:44
@denfromufa I have run into the same issue, running Windows 10, python3.6, and the current version of pythonnet from github.  I confirmed that python3.6 is in my PATH, and is set as my environment on Visual Studio.  After building from source, I tried running nPython.exe, and got the same error seen above.

**Comment by denfromufa** [comment] 2017-11-30 21:33
Did you read the troubleshooting wiki?

**Comment by jengelman** [comment] 2017-12-01 15:41
@denfromufa switching to the ReleaseWinPY3 build config worked, thanks!

**Comment by denfromufa** [comment] 2017-12-01 15:51
@jengelman greast, don't forget to star this repo!

**Comment by denfromufa** [comment] 2017-12-01 15:52
@jengelman great, don't forget to star this repo!
